---
sidebar: sidebar 
permalink: whats-new.html 
keywords: 'what"s new, features, new, release notes, enhancements, fixes, new features,cloud manager, bluexp, cloud volumes ontap, licenses, digital wallet, subscriptions, cloud backup, cloud tiering, data sense, ransomware, connector, amazon fsx for ontap, azure netapp files, cloud sync, e-series, global file cache, google cloud, disaster recovery, backup and recovery, classification, copy and sync, edge cache, edge caching, volume caching, ontap clusters, alerts, identity and access management, iam' 
summary: BlueXP 플랫폼의 일부인 클라우드 서비스의 최신 변경 사항에 대해 알아보십시오. 
---
= BlueXP의 최근 변경 사항
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
BlueXP 플랫폼의 일부인 클라우드 서비스의 최신 변경 사항에 대해 알아보십시오. 전체 릴리스 기록을 보려면 로 이동하십시오 link:release-notes-index.html["전체 릴리스 정보 세트"] 각 개별 서비스에 대해.



== 관리 기능

이 섹션에서는 계정, 커넥터, 클라우드 공급자 자격 증명 등과 같은 BlueXP 관리 기능과 관련된 새로운 기능에 대해 설명합니다.



=== 2025년 5월 12일



==== 커넥터 3.9.52

이 BlueXP  커넥터 릴리스에는 사소한 보안 개선 사항 및 버그 수정 사항, 몇 가지 추가 업데이트가 포함되어 있습니다.

현재 3.9.52 릴리스는 표준 모드 및 제한 모드에서 사용할 수 있습니다.



===== Docker 27 및 Docker 28을 지원합니다

Docker 27 및 Docker 28이 이제 커넥터에서 지원됩니다.



==== BlueXP 에서 Keystone 관리 기능 제공

BlueXP 에서 NetApp Keystone를 위한 베타에서 Keystone 관리에 대한 액세스 권한이 추가되었습니다. BlueXP 의 왼쪽 탐색 모음에서 NetApp Keystone 베타의 등록 페이지에 액세스할 수 있습니다.



=== 2025년 4월 14일



==== 커넥터 3.9.51

이번 BlueXP Connector 릴리즈에는 사소한 보안 개선사항과 버그 수정이 포함되어 있습니다.

현재 3.9.51 릴리스는 표준 모드 및 제한 모드에서 사용할 수 있습니다.



==== BlueXP  ID 및 액세스 관리(IAM)

* 조직 관리자 또는 폴더 또는 프로젝트 관리자가 없는 사용자는 랜섬웨어 방어 역할을 할당해야 랜섬웨어 방지에 액세스할 수 있습니다. 사용자에게 랜섬웨어 차단 관리자 또는 랜섬웨어 차단 뷰어의 두 가지 역할 중 하나를 할당할 수 있습니다.
* 조직 관리자 또는 폴더 또는 프로젝트 관리자가 없는 사용자에게는 Keystone 역할이 할당되어야 Keystone에 액세스할 수 있습니다. 사용자에게 Keystone admin 또는 Keystone 뷰어의 두 가지 역할 중 하나를 할당할 수 있습니다.
+
link:https://docs.netapp.com/us-en/bluexp-setup-admin/reference-iam-predefined-roles.html["액세스 역할에 대해 알아봅니다."^]

* 조직 관리자 또는 폴더 또는 프로젝트 관리자 역할이 있는 경우 이제 Keystone 구독을 IAM 프로젝트에 연결할 수 있습니다. Keystone 구독과 IAM 프로젝트를 연결하면 BlueXP  내에서 Keystone에 대한 액세스를 제어할 수 있습니다.




=== 2025년 3월 28일



==== 비공개 모드 해제(3.9.50)

이제 에서 새 비공개 모드 릴리스를 다운로드할 수 있습니다 https://mysupport.netapp.com/site/downloads["NetApp Support 사이트"^]

3.9.50 릴리스에는 다음 BlueXP  구성 요소 및 서비스에 대한 업데이트가 포함되어 있습니다.

[cols="3*"]
|===
| 구성 요소 또는 서비스 | 이 릴리스에 포함된 버전입니다 | 이전 비공개 모드 릴리스 이후 변경된 사항입니다 


| 커넥터 | 3.9.50, 3.9.49 | 로 https://docs.netapp.com/us-en/bluexp-setup-admin/whats-new.html#connector-3-9-50["BlueXP  커넥터 페이지의 새로운 기능"] 이동하여 버전 3.9.50 및 3.9.49에 포함된 변경 사항을 참조하십시오. 


| 백업 및 복구 | 2025년 3월 17일 | 로 https://docs.netapp.com/us-en/bluexp-backup-recovery/whats-new.html["BlueXP  백업 및 복구 페이지의 새로운 기능"^] 이동하여 2024년 3월 릴리즈에 포함된 변경 사항을 참조하십시오. 


| 분류 | 2025년 3월 10일(버전 1.41) | 로 https://docs.netapp.com/us-en/bluexp-classification/whats-new.html["BlueXP  분류 페이지의 새로운 기능"^] 이동하여 1.38 - 1.371.41 릴리스에 포함된 변경 사항을 참조하십시오. 
|===
업그레이드 방법을 포함하여 개인 모드에 대한 자세한 내용은 다음을 참조하십시오.

* https://docs.netapp.com/us-en/bluexp-setup-admin/concept-modes.html["비공개 모드에 대해 알아봅니다"]
* https://docs.netapp.com/us-en/bluexp-setup-admin/task-quick-start-private-mode.html["프라이빗 모드에서 BlueXP를 시작하는 방법을 알아보십시오"]
* https://docs.netapp.com/us-en/bluexp-setup-admin/task-upgrade-connector.html["비공개 모드를 사용할 때 커넥터를 업그레이드하는 방법에 대해 알아봅니다"]




== 경고



=== 2024년 10월 7일



==== BlueXP  알림 목록 페이지

용량이 낮거나 성능이 낮은 ONTAP 클러스터를 신속하게 식별하고, 가용성 범위를 판단하며, 보안 위험을 식별할 수 있습니다. 용량, 성능, 보호, 가용성, 보안 및 구성과 관련된 경고를 볼 수 있습니다.



==== 경고 세부 정보

알림 세부 정보를 상세히 파악하고 권장 사항을 찾을 수 있습니다.



==== ONTAP System Manager에 연결된 클러스터 세부 정보를 봅니다

BlueXP  경고를 사용하면 ONTAP 스토리지 환경과 연결된 경고를 확인하고 ONTAP System Manager에 연결된 세부 정보를 드릴다운할 수 있습니다.

https://docs.netapp.com/us-en/bluexp-alerts/concept-alerts.html["BlueXP  알림에 대해 자세히 알아봅니다"]..



== ONTAP용 Amazon FSx



=== 2025년 5월 4일



==== Tracker 응답 지원

이제 추적기는 작업과 관련된 REST API 출력을 볼 수 있도록 API 응답을 제공합니다.



==== AWS Secrets Manager에 대한 링크 인증 지원

이제 AWS Secrets Manager의 비밀을 사용하여 링크를 인증할 수 있으므로 BlueXP  워크로드에 저장된 자격 증명을 사용할 필요가 없습니다.

link:https://docs.netapp.com/us-en/workload-fsx-ontap/create-link.html["Lambda 링크를 사용하여 FSx for ONTAP 파일 시스템에 연결합니다"]



==== FSx for ONTAP 파일 시스템에 대한 모범 사례 구현

BlueXP  워크로드는 파일 시스템 구성의 체계적으로 상태를 검토할 수 있는 대시보드를 제공합니다. 이 분석을 활용하여 FSx for ONTAP 파일 시스템에 대한 모범 사례를 구현할 수 있습니다. 파일 시스템 구성 분석에는 SSD 용량 임계값, 예약된 로컬 스냅샷, 예약된 FSx for ONTAP 백업, 데이터 계층화, 원격 데이터 복제 구성이 포함됩니다.

* link:https://docs.netapp.com/us-en/workload-fsx-ontap/configuration-analysis.html["파일 시스템 구성을 위한 잘 설계된 분석에 대해 알아보십시오"]
* link:https://review.docs.netapp.com/us-en/workload-fsx-ontap_well-architected/improve-configurations.html["파일 시스템에 대한 모범 사례 구현"]




==== 파일 시스템 문제에 대한 체계적인 알림

이제 BlueXP  콘솔에서 잘 설계된 문제가 있는 FSx for ONTAP 파일 시스템의 경우 파일 시스템에서 해결해야 할 문제가 언제 발생하는지를 나타내는 알림이 Canvas에 표시됩니다.



==== 사용 권한 용어가 업데이트되었습니다

워크로드 팩토리 사용자 인터페이스 및 설명서에서는 이제 "읽기 전용"을 사용하여 읽기 권한을 참조하고 "읽기-쓰기"를 사용하여 사용 권한을 자동화합니다.



=== 2025년 3월 30일



==== IAM: SimulatePermissionPolicy 권한 업데이트

이제 AWS 계정 자격 증명을 추가하거나 GenAI 워크로드와 같은 새로운 워크로드 기능을 추가할 때 BlueXP  콘솔에서 권한을 관리할 수 있습니다 `iam:SimulatePrincipalPolicy`.

link:https://docs.netapp.com/us-en/workload-setup-admin/permissions-reference.html#change-log["권한 참조 변경 로그"^]



=== 2025년 3월 2일



==== Tracker의 CloudShell 이벤트

CloudShell을 사용하여 BlueXP  워크로드에서 FSx for ONTAP 작업을 실행할 때 Tracker에 이벤트가 표시됩니다.

link:https://docs.netapp.com/us-en/bluexp-fsx-ontap/use/task-monitor-operations.html["BlueXP 에서 FSx for ONTAP 운영을 모니터링하고 추적하는 방법에 관해 알아보십시오"^]



== Amazon S3 스토리지



=== 2023년 3월 5일



==== BlueXP에서 새 버킷을 추가할 수 있습니다

BlueXP Canvas에서 Amazon S3 버킷을 잠시 볼 수 있었습니다. 이제 BlueXP 에서 직접 새 버킷을 추가하고 기존 버켓의 속성을 변경할 수 있습니다. https://docs.netapp.com/us-en/bluexp-s3-storage/task-add-s3-bucket.html["새 Amazon S3 버킷을 추가하는 방법을 알아보십시오"]..



== Azure Blob 저장소



=== 2023년 6월 5일



==== BlueXP에서 새 스토리지 계정을 추가할 수 있습니다

BlueXP Canvas에서 Azure Blob Storage를 한동안 볼 수 있는 기능이 있습니다. 이제 BlueXP 에서 직접 새 스토리지 계정을 추가하고 기존 스토리지 계정의 속성을 변경할 수 있습니다. https://docs.netapp.com/us-en/bluexp-blob-storage/task-add-blob-storage.html["새 Azure Blob 저장소 계정을 추가하는 방법을 알아보십시오"]..



== Azure NetApp Files



=== 2025년 1월 13일



==== 이제 BlueXP 에서 네트워크 기능이 지원됩니다

BlueXP 의 Azure NetApp Files에서 볼륨을 구성할 때 이제 네트워크 기능을 지정할 수 있습니다. 이는 네이티브 Azure NetApp Files에서 제공되는 기능에 맞게 조정됩니다.



=== 2024년 6월 12일



==== 새 권한이 필요합니다

이제 BlueXP에서 Azure NetApp Files 볼륨을 관리하려면 다음 권한이 필요합니다.

Microsoft.Network/virtualNetworks/subnets/read

가상 네트워크 서브넷을 읽으려면 이 권한이 필요합니다.

현재 BlueXP에서 Azure NetApp Files를 관리하고 있는 경우 이전에 생성한 Microsoft Entra 애플리케이션과 연결된 사용자 지정 역할에 이 권한을 추가해야 합니다.

https://docs.netapp.com/us-en/bluexp-azure-netapp-files/task-set-up-azure-ad.html["Microsoft Entra 응용 프로그램을 설정하고 사용자 지정 역할 권한을 보는 방법에 대해 알아봅니다"]..



=== 2024년 4월 22일



==== 볼륨 템플릿은 더 이상 지원되지 않습니다

더 이상 템플릿에서 볼륨을 생성할 수 없습니다. 이 작업은 BlueXP 해결 서비스와 연계되었으며, 더 이상 사용할 수 없습니다.



== 백업 및 복구



=== 2025년 4월 16일

이 BlueXP  백업 및 복구 릴리스에는 다음 업데이트가 포함되어 있습니다.



==== UI 개선

이 릴리스는 인터페이스를 단순화함으로써 사용자 경험을 향상시킵니다.

* 볼륨 테이블에서 애그리게이트 열을 제거하고 V2 대시보드의 볼륨 테이블에서 스냅샷 정책, 백업 정책 및 복제 정책 열을 제거하면 레이아웃이 보다 간소화됩니다.
* 드롭다운 목록에서 활성화되지 않은 작업 환경을 제외하면 인터페이스가 덜 복잡해지고 탐색이 더 효율적으로 수행되며 로딩 속도가 빨라집니다.
* 태그 열에서 정렬을 사용할 수 없지만 중요한 정보에 쉽게 액세스할 수 있도록 태그를 계속 볼 수 있습니다.
* 보호 아이콘의 라벨을 제거하면 더 깔끔한 외관을 연출하고 로딩 시간을 줄일 수 있습니다.
* 작업 환경 활성화 프로세스 중에 대화 상자에 로드 아이콘이 표시되어 검색 프로세스가 완료될 때까지 피드백을 제공하여 시스템 운영에 대한 투명성과 신뢰도를 높입니다.




==== 향상된 볼륨 대시보드(미리 보기)

이제 볼륨 대시보드가 10초 이내에 로드되므로 훨씬 빠르고 효율적인 인터페이스를 제공합니다. 이 Preview 버전은 일부 고객에게 제공되며 이러한 개선 사항을 조기에 확인할 수 있습니다.



==== 타사 Wasabi 개체 저장소 지원(Preview)

BlueXP  백업 및 복구는 이제 Wasabi에 중점을 두고 타사 오브젝트 스토어까지 지원을 확장하고 있습니다. 이 새로운 미리 보기 기능을 사용하면 백업 및 복구 요구에 S3 호환 오브젝트 저장소를 활용할 수 있습니다.



===== Wasabi 시작하기

타사 스토리지를 개체 저장소로 사용하려면 BlueXP  커넥터 내에서 플래그를 설정해야 합니다. 그런 다음 타사 오브젝트 저장소에 대한 연결 정보를 입력하고 백업 및 복구 워크플로에 통합할 수 있습니다.

.단계
. SSH를 사용하여 커넥터에 연결합니다.
. BlueXP  백업 및 복구 CBS 서버 컨테이너로 이동합니다.
+
[listing]
----
docker exec -it cloudmanager_cbs sh
----
. VIM 또는 다른 편집기를 통해 폴더 내에서 파일을 `config` 엽니다 `default.json`.
+
[listing]
----
vi default.json
----
. modify `allow-s3-compatible`:false to:true로 `allow-s3-compatible` 변경합니다.
. 변경 사항을 저장합니다.
. 컨테이너에서 나갑니다.
. BlueXP  백업 및 복구 CBS 서버 컨테이너를 다시 시작합니다.


.결과
컨테이너가 다시 켜지면 BlueXP  백업 및 복구 UI를 엽니다. 백업을 시작하거나 백업 전략을 편집하면 AWS, Microsoft Azure, Google Cloud, StorageGRID 및 ONTAP S3의 다른 백업 공급자와 함께 새로운 공급업체 "S3 호환"이 표시됩니다.



===== 미리보기 모드 제한

이 기능이 미리 보기에 있는 동안 다음 제한 사항을 고려하십시오.

* BYOB(Bring Your Own Bucket)는 지원되지 않습니다.
* 정책에서 DataLock을 사용하도록 설정할 수 없습니다.
* 정책에서 아카이브 모드를 사용하도록 설정하는 것은 지원되지 않습니다.
* 온프레미스 ONTAP 환경만 지원됩니다.
* MetroCluster는 지원되지 않습니다.
* 버킷 수준 암호화를 활성화하는 옵션은 지원되지 않습니다.


이 미리 보기를 진행하는 동안 이 새로운 기능을 살펴보고 전체 기능이 배포되기 전에 타사 개체 저장소와의 통합에 대한 피드백을 제공하는 것이 좋습니다.



=== 2025년 3월 17일

이 BlueXP  백업 및 복구 릴리스에는 다음 업데이트가 포함되어 있습니다.



==== SMB 스냅샷 탐색

이 BlueXP  백업 및 복구 업데이트는 고객이 SMB 환경에서 로컬 스냅샷을 찾을 수 없는 문제를 해결했습니다.



==== AWS GovCloud 환경 업데이트

이 BlueXP  백업 및 복구 업데이트는 TLS 인증서 오류로 인해 UI가 AWS GovCloud 환경에 연결되지 않는 문제를 해결했습니다. IP 주소 대신 BlueXP  커넥터 호스트 이름을 사용하여 문제를 해결했습니다.



==== 백업 정책 보존 제한

이전에는 BlueXP  백업 및 복구 UI에서 백업을 999개로 제한했지만 CLI에서는 백업을 더 허용했습니다. 이제 최대 4,000개의 볼륨을 백업 정책에 연결할 수 있으며 백업 정책에 연결되지 않은 1,018개의 볼륨을 포함할 수 있습니다. 이 업데이트에는 이러한 제한을 초과하지 않는 추가 유효성 검사가 포함되어 있습니다.



==== SnapMirror Cloud 재동기화

이 업데이트는 SnapMirror 관계가 삭제된 후에 지원되지 않는 ONTAP 버전에 대한 BlueXP  백업 및 복구에서 SnapMirror Cloud 재동기화를 시작할 수 없도록 합니다.



=== 2025년 2월 21일

이 BlueXP  백업 및 복구 릴리스에는 다음 업데이트가 포함되어 있습니다.



==== 고성능 인덱싱

BlueXP  백업 및 복구에는 소스 작업 환경에서 데이터를 보다 효율적으로 인덱싱할 수 있는 업데이트된 인덱싱 기능이 도입되었습니다. 새로운 인덱싱 기능에는 UI 업데이트, 데이터 복원 검색 및 복원 방법의 향상된 성능, 글로벌 검색 기능으로 업그레이드 및 향상된 확장성 등이 포함됩니다.

개선된 사항은 다음과 같습니다.

* * 폴더 통합 *: 업데이트된 버전은 특정 식별자가 포함된 이름을 사용하여 폴더를 그룹화하여 인덱싱 프로세스를 원활하게 합니다.
* * Parquet 파일 압축 *: 업데이트된 버전은 각 볼륨을 인덱싱하는 데 사용되는 파일 수를 줄여 프로세스를 단순화하고 추가 데이터베이스가 필요하지 않습니다.
* * 더 많은 세션으로 스케일 아웃 *: 새로운 버전은 인덱싱 작업을 처리하기 위해 더 많은 세션을 추가하여 프로세스 속도를 높입니다.
* * 다중 인덱스 컨테이너 지원 * : 새 버전은 인덱싱 작업을 더 잘 관리하고 배포하기 위해 여러 컨테이너를 사용합니다.
* * 분할 색인 워크플로 * : 새 버전은 인덱싱 프로세스를 두 부분으로 분할하여 효율성을 향상시킵니다.
* * 향상된 동시성 * : 새로운 버전을 사용하면 동시에 디렉토리를 삭제하거나 이동할 수 있으므로 인덱싱 프로세스가 빨라집니다.


.이 기능의 이점은 누구입니까?
새로운 인덱싱 기능은 모든 신규 고객이 사용할 수 있습니다.

.인덱싱을 활성화하려면 어떻게 해야 합니까?
데이터를 복원하는 검색 및 복원 방법을 사용하려면 먼저 볼륨 또는 파일을 복원하려는 각 소스 작업 환경에서 "인덱싱"을 활성화해야 합니다. 따라서 인덱스화된 카탈로그가 모든 볼륨과 모든 백업 파일을 추적할 수 있어 빠르고 효율적으로 검색할 수 있습니다.

검색 및 복원을 수행할 때 "인덱싱 사용" 옵션을 선택하여 소스 작업 환경에서 인덱싱을 활성화합니다.

자세한 내용은 설명서를 https://docs.netapp.com/us-en/bluexp-backup-recovery/task-restore-backups-ontap.html#restore-ontap-data-using-search-restore["검색 및 복원 을 사용하여 ONTAP 데이터를 복원하는 방법"]참조하십시오.

.지원되는 배율
새 인덱싱 기능은 다음을 지원합니다.

* 3분 이내에 글로벌 검색 효율성 향상
* 최대 50억 개의 파일
* 클러스터당 최대 5000개의 볼륨
* 볼륨당 최대 100,000개의 스냅샷 지원
* 기준 색인에 대한 최대 시간은 7일 미만입니다. 실제 시간은 환경에 따라 다릅니다.




==== 글로벌 검색 성능 향상

이번 릴리스에는 글로벌 검색 성능 향상도 포함되어 있습니다. 이제 진행률 표시기 및 파일 수와 검색에 걸리는 시간을 포함하여 보다 자세한 검색 결과가 표시됩니다. 검색 및 색인화를 위한 전용 컨테이너를 통해 5분 이내에 글로벌 검색이 완료됩니다.

글로벌 검색과 관련된 고려 사항은 다음과 같습니다.

* 새 인덱스는 시간별 스냅샷으로 레이블이 지정된 스냅샷에 대해 수행되지 않습니다.
* 새로운 인덱싱 기능은 FlexVol의 스냅샷에만 작동하며, FlexGroups의 스냅샷에는 작동하지 않습니다.




== 분류



=== 2025년 5월 12일



==== 버전 1.43

이 BlueXP  분류 릴리스에는 다음이 포함됩니다.

.분류 스캔의 우선 순위를 지정합니다
이제 BlueXP  분류는 매핑 전용 스캔뿐만 아니라 스캔 지도 및 분류 우선 순위를 지정할 수 있는 기능을 지원하므로 먼저 완료된 스캔을 선택할 수 있습니다. 맵 및 분류 스캔의 우선 순위는 스캔이 시작되는 동안과 그 전에 지원됩니다. 스캔이 진행 중일 때 스캔 우선 순위를 지정하도록 선택하면 매핑 및 분류 스캔이 모두 우선 순위가 지정됩니다.

자세한 내용은 을 link:task-managing-repo-scanning.html#prioritize-scans["스캔 우선 순위 지정"]참조하십시오.

.캐나다 PII(개인 식별 정보) 데이터 범주 지원
BlueXP  분류 검사는 이제 모든 주 및 지역에 대한 은행 정보, 여권 번호, 사회 보험 번호, 운전 면허 번호 및 건강 카드 번호에 대한 캐나다 PII 데이터 범주를 식별합니다.

자세한 내용은 을 참조하십시오xref:reference-private-data-categories.adoc#types-of-personal-data[개인 데이터 범주].

.사용자 지정 분류(미리 보기)
이제 BlueXP  분류는 지도 및 분류 스캔에 대한 사용자 정의 분류를 지원합니다. 사용자 지정 분류를 사용하면 BlueXP  스캔을 사용자 지정하여 정규식을 준수하도록 조직별 데이터를 캡처할 수 있습니다. 이 기능은 현재 미리보기 중입니다.

자세한 내용은 을 xref:task-custom-classification.adoc[사용자 지정 분류를 추가합니다]참조하십시오.

.저장된 검색 탭
** Policies** 탭의 이름이 xref:task-using-policies.html[** 저장된 검색**]변경되었습니다. 기능은 동일합니다.

.스캔 이벤트를 BlueXP  타임라인으로 보냅니다
이제 BlueXP  분류는 에 분류 이벤트(스캔이 시작되었을 때와 종료되었을 때)를 보낼 수 있도록 link:https://docs.netapp.com/us-en/bluexp-setup-admin/task-monitor-cm-operations.html#audit-user-activity-from-the-bluexp-timeline["BlueXP  타임라인"^]지원합니다.

.보안 업데이트
* Keras 패키지가 업데이트되어 취약점을 완화합니다(BDSA-2025-0107 및 BDSA-2025-1984).
* Docker 컨테이너 구성이 업데이트되었습니다. 컨테이너는 더 이상 원시 네트워크 패킷을 만들기 위해 호스트의 네트워크 인터페이스에 액세스할 수 없습니다. 이 업데이트는 불필요한 액세스를 줄여 잠재적인 보안 위험을 완화합니다.


.성능 향상
RAM 사용을 줄이고 BlueXP  분류의 전반적인 성능을 개선하기 위해 코드 개선 사항이 구현되었습니다.

.버그 수정
StorageGRID 검사가 실패하고, 조사 페이지 필터 옵션이 로드되지 않으며, 대량 평가를 위해 다운로드되지 않는 데이터 검색 평가가 수정되었습니다.



=== 2025년 4월 14일



==== 버전 1.42

이 BlueXP  분류 릴리스에는 다음이 포함됩니다.

.작업 환경을 위한 대량 스캔
BlueXP  분류는 이제 작업 환경에 대한 대량 작업을 지원합니다. 스캔 매핑 활성화, 스캔 매핑 및 분류 활성화, 스캔 비활성화 또는 작업 환경의 볼륨에 대한 사용자 정의 구성 생성을 선택할 수 있습니다. 개별 볼륨에 대해 선택하면 대량 선택이 무시됩니다. 대량 작업을 수행하려면 ** 구성** 페이지로 이동하여 선택합니다.

.조사 보고서를 로컬로 다운로드합니다
이제 BlueXP  분류는 데이터 조사 보고서를 로컬로 다운로드하여 브라우저에서 볼 수 있는 기능을 지원합니다. 로컬 옵션을 선택하면 데이터 조사는 CSV 형식으로만 사용할 수 있으며 처음 10,000개의 데이터 행만 표시됩니다.

자세한 내용은 을 link:task-investigate-data.html#create-the-data-investigation-report["BlueXP  분류를 통해 조직에 저장된 데이터를 조사합니다"]참조하십시오.



=== 2025년 3월 10일



==== 버전 1.41

이 BlueXP  분류 릴리스에는 일반적인 개선 사항 및 버그 수정이 포함되어 있습니다. 여기에는 다음이 포함됩니다.

.스캔 상태
이제 BlueXP  분류는 볼륨에서 _initial_mapping 및 분류 스캔의 실시간 진행률을 추적합니다. 별도의 프로그레시브 바는 매핑 및 분류 스캔을 추적하여 스캔된 총 파일의 백분율을 표시합니다. 진행 표시줄 위로 마우스를 가져가면 스캔한 파일 수와 총 파일 수를 볼 수도 있습니다. 스캔 상태를 추적하면 스캔 진행 상황을 더 자세히 파악할 수 있으므로 스캔 계획을 개선하고 리소스 할당을 이해할 수 있습니다.

스캔 상태를 보려면 BlueXP  분류에서 ** 구성**으로 이동한 다음 ** 작업 환경 구성** 을 선택합니다. 진행 상황은 각 볼륨에 대해 일렬로 표시됩니다.



=== 2025년 2월 19일



==== 버전 1.40

이 BlueXP  분류 릴리스에는 다음 업데이트가 포함됩니다.

.RHEL 9.5 지원
이 릴리스는 Red Hat Enterprise Linux v9.5 및 이전에 지원되는 버전을 지원합니다. 이는 다크 사이트 배포를 포함하여 BlueXP  분류의 수동 온-프레미스 설치에 적용됩니다.

다음 운영 체제는 Podman 컨테이너 엔진을 사용해야 하며 BlueXP  분류 버전 1.30 이상이 필요합니다. Red Hat Enterprise Linux 버전 8.8, 8.10, 9.0, 9.1, 9.2, 9.3, 9.4 및 9.5.

.매핑 전용 스캔의 우선 순위를 지정합니다
매핑 전용 스캔을 수행할 때 가장 중요한 스캔의 우선 순위를 지정할 수 있습니다. 이 기능은 작업 환경이 많고 우선 순위가 높은 검사가 먼저 완료되도록 하려는 경우에 유용합니다.

기본적으로 스캔은 시작된 순서에 따라 대기합니다. 스캔 우선 순위 지정 기능을 통해 이제 스캔을 대기열 앞으로 이동할 수 있습니다. 여러 스캔의 우선 순위를 지정할 수 있습니다. 우선 순위는 선입선출 순서로 지정됩니다. 즉, 우선 순위를 지정한 첫 번째 스캔이 대기열의 맨 앞으로 이동하고 우선 순위를 지정한 두 번째 스캔은 대기열의 두 번째 스캔이 됩니다.

우선 순위는 한 번만 부여됩니다. 매핑 데이터의 자동 재검색이 기본 순서로 수행됩니다.

우선 순위 지정은 로 link:concept-cloud-compliance.html["매핑 전용 스캔"]제한됩니다. 스캔 맵과 분류에는 사용할 수 없습니다.

자세한 내용은 을 link:task-managing-repo-scanning.html#prioritize-scans["스캔 우선 순위 지정"]참조하십시오.

.모든 스캔을 재시도합니다
이제 BlueXP  분류는 실패한 모든 스캔을 일괄 재시도하는 기능을 지원합니다.

이제 ** Retry All** 기능을 사용하여 일괄 작업으로 스캔을 다시 시도할 수 있습니다. 네트워크 중단과 같은 일시적인 문제로 인해 분류 스캔이 실패하는 경우 개별적으로 다시 시도하지 않고 하나의 버튼으로 모든 스캔을 동시에 다시 시도할 수 있습니다. 스캔은 필요한 만큼 재시도할 수 있습니다.

모든 스캔을 재시도하려면:

. BlueXP  classification 메뉴에서 * Configuration * 을 선택합니다.
. 실패한 모든 스캔을 다시 시도하려면 * 모든 스캔 재시도 * 를 선택합니다.


.범주화 모델 정확도 향상
의 머신 러닝 모델의 정확도는 link:https://docs.netapp.com/us-en/bluexp-classification/reference-private-data-categories.html#types-of-sensitive-personal-datapredefined-categories["미리 정의된 범주"]11% 향상되었습니다.



=== 2025년 1월 22일



==== 버전 1.39

이 BlueXP  분류 릴리스는 데이터 조사 보고서의 내보내기 프로세스를 업데이트합니다. 이 내보내기 업데이트는 데이터에 대한 추가 분석을 수행하거나, 데이터에 대한 추가 시각화를 만들거나, 데이터 조사 결과를 다른 사람과 공유하는 데 유용합니다.

이전에는 데이터 조사 보고서 내보내기가 10,000행으로 제한되었습니다. 이 릴리스에서는 모든 데이터를 내보낼 수 있도록 제한이 제거되었습니다. 이 변경 사항을 통해 데이터 조사 보고서에서 더 많은 데이터를 내보낼 수 있으므로 보다 유연하게 데이터를 분석할 수 있습니다.

작업 환경, 볼륨, 대상 폴더 및 JSON 또는 CSV 형식을 선택할 수 있습니다. 내보낸 파일 이름에는 타임스탬프가 포함되어 있어 데이터를 내보낸 시기를 식별할 수 있습니다.

지원되는 작업 환경은 다음과 같습니다.

* Cloud Volumes ONTAP
* ONTAP용 FSX
* ONTAP
* 공유 그룹


데이터 조사 보고서에서 데이터를 내보내는 데는 다음과 같은 제한 사항이 있습니다.

* 다운로드할 최대 레코드 수는 유형(파일, 디렉터리 및 테이블)당 5억 개입니다.
* 100만 개의 레코드를 내보내는 데 약 35분이 걸릴 것으로 예상됩니다.


데이터 조사 및 보고서에 대한 자세한 내용은 을 참조하십시오 https://docs.netapp.com/us-en/bluexp-classification/task-investigate-data.html["조직에 저장된 데이터를 조사합니다"].



=== 2024년 12월 16일



==== 버전 1.38

이 BlueXP  분류 릴리스에는 일반적인 개선 사항 및 버그 수정이 포함되어 있습니다.



== Cloud Volumes ONTAP



=== 2025년 5월 12일



==== BlueXP 에서 Azure 마켓플레이스를 통해 이루어진 배포를 검색합니다

BlueXP 에는 이제 Azure 마켓플레이스를 통해 직접 배포된 Cloud Volumes ONTAP 시스템을 검색할 수 있는 기능이 있습니다. 즉, 다른 모든 Cloud Volumes ONTAP 시스템과 마찬가지로 이제 이러한 시스템을 BlueXP 의 작업 환경으로 추가하고 관리할 수 있습니다.

https://docs.netapp.com/us-en/bluexp-cloud-volumes-ontap/task-deploy-cvo-azure-mktplc.html["Azure 마켓플레이스에서 Cloud Volumes ONTAP을 배포합니다"^]



==== Azure 테넌트의 데이터를 계층화하는 기능

이제 한 테넌트에 의해 Cloud Volumes ONTAP 작업 환경이 생성되고 다른 테넌트에 의해 BlueXP  커넥터가 생성되는 시나리오에서 Azure 테넌트에 대한 계층화를 활성화할 수 있습니다. 이 기능을 사용하면 동일한 Connector를 사용하여 여러 Azure 테넌트의 데이터를 계층화할 수 있습니다.

https://docs.netapp.com/us-en/bluexp-cloud-volumes-ontap/task-tiering.html#requirements-to-tier-data-for-an-azure-tenant["Azure 테넌트의 데이터를 계층화하기 위한 요구사항"^]



=== 2025년 4월 16일



==== Azure에서 새로운 영역이 지원됩니다

이제 다음 지역에 있는 Azure에서 단일 및 여러 가용 영역에 Cloud Volumes ONTAP 9.12.1 GA 이상을 배포할 수 있습니다. 여기에는 단일 노드 및 고가용성(HA) 구축이 모두 지원됩니다.

* 스페인 중부
* 멕시코 중부


모든 지역의 목록은 을 https://bluexp.netapp.com/cloud-volumes-global-regions["Azure 아래의 글로벌 지역 지도"^]참조하십시오.



=== 2025년 4월 14일



==== Google Cloud의 API를 통해 스토리지 VM 생성을 자동화합니다

이제 BlueXP  API를 사용하여 Google Cloud에서 스토리지 VM 생성을 자동화할 수 있습니다. Cloud Volumes ONTAP 고가용성(HA) 구성에서 이 기능을 사용해왔으며, 이제 단일 노드 구축에서도 사용할 수 있습니다. BlueXP  API를 사용하면 필요한 네트워크 인터페이스, LIF 및 관리 LIF를 수동으로 구성할 필요 없이 Google Cloud 환경에서 데이터 제공 스토리지 VM을 쉽게 생성, 이름 변경 및 삭제할 수 있습니다. 이러한 자동화는 스토리지 VM 관리 프로세스를 간소화합니다.

https://docs.netapp.com/us-en/bluexp-cloud-volumes-ontap/task-managing-svms-gcp.html["Google Cloud에서 Cloud Volumes ONTAP용 데이터 서비스 스토리지 VM을 관리합니다"^]



== Google Cloud용 Cloud Volumes Service



=== 2020년 9월 9일



==== Cloud Volumes Service for Google Cloud 지원

이제 BlueXP에서 직접 Cloud Volumes Service for Google Cloud를 관리할 수 있습니다.

* 작업 환경 설정 및 생성
* Linux 및 UNIX 클라이언트용 NFSv3 및 NFSv4.1 볼륨을 생성하고 관리합니다
* Windows 클라이언트용 SMB 3.x 볼륨을 생성하고 관리합니다
* 볼륨 스냅숏을 생성, 삭제 및 복원합니다




== 복사 및 동기화



=== 2025년 2월 2일



==== 데이터 브로커를 위한 새로운 OS 지원

이제 Red Hat Enterprise 9.4, Ubuntu 23.04 및 Ubuntu 24.04를 실행하는 호스트에서 데이터 브로커가 지원됩니다.

https://docs.netapp.com/us-en/bluexp-copy-sync/task-installing-linux.html#linux-host-requirements["Linux 호스트 요구 사항 보기"]..



=== 2024년 10월 27일



==== 버그 수정

BlueXP 복사본 및 동기화 서비스와 데이터 브로커를 업데이트하여 몇 가지 버그를 수정했습니다. 새 데이터 브로커 버전은 1.0.56입니다.



=== 2024년 9월 16일



==== 버그 수정

BlueXP 복사본 및 동기화 서비스와 데이터 브로커를 업데이트하여 몇 가지 버그를 수정했습니다. 새 데이터 브로커 버전은 1.0.55입니다.



== 디지털 자문업체



=== 2025년 3월 5일



==== Upgrade Advisor

* 이제 디스크 자격 평가 패키지(DQP)를 사용하여 미리 정의된 상태 및 성능 기준에 따라 디스크 컨트롤러와 스토리지 장치 펌웨어를 자동으로 업데이트할 수 있습니다. 이로 인해 잠재적인 오류가 줄어들고 전반적인 시스템 안정성이 향상됩니다.
* 최신 표준 시간대 정의와 시스템 정렬을 자동으로 유지하기 위해 표준 시간대 데이터베이스(DB)가 도입되었습니다. 이렇게 하면 시간대 규칙이 변경되더라도 시간 종속 작업이 원활하게 진행됩니다.




=== 2024년 12월 12일



==== Upgrade Advisor

이제 업데이트에 권장되는 스토리지 펌웨어, SP/BMC 펌웨어 및 ARP(자율적 랜섬웨어 패키지)를 볼 수 있습니다. link:https://docs.netapp.com/us-en/active-iq/view-firmware-update-recommendations.html["펌웨어 업데이트 권장 사항을 보는 방법에 대해 알아봅니다"]..



=== 2024년 12월 4일



==== AutoSupport 위젯

AutoSupport 상태 관련 문제를 고객에게 알리기 위해 AutoSupport 위젯이 기본 대시보드 화면에 추가되었습니다.



== 디지털 지갑



=== 2025년 3월 10일



==== 구독을 제거할 수 있습니다

이제 구독을 취소한 경우 디지털 지갑에서 구독을 제거할 수 있습니다.



==== 마켓플레이스 구독에 사용된 용량 보기

PAYGO 서브스크립션을 볼 때 서브스크립션의 소비 용량을 볼 수 있습니다.



=== 2025년 2월 10일

BlueXP  디지털 지갑은 사용하기 쉽도록 다시 디자인되었으며 이제 추가 구독 및 라이선스 관리 기능을 제공합니다.



==== 새로운 개요 대시보드

디지털 지갑 홈페이지에는 NetApp 라이선스 및 마켓플레이스 구독에 대한 업데이트된 대시보드가 있으며, 특정 서비스, 라이선스 유형 및 필요한 작업을 드릴다운할 수 있습니다.



==== 자격 증명에 대한 구독을 구성하는 중입니다

이제 BlueXP  디지털 지갑을 사용하여 공급자 자격 증명에 대한 구독을 구성할 수 있습니다. 일반적으로 마켓플레이스 구독 또는 연간 계약을 처음 구독할 때 이 작업을 수행합니다. 이전에는 구독 자격 증명을 변경할 수 있었습니다. 자격 증명 페이지에서만 변경할 수 있었습니다.



==== 구독을 조직과 연결합니다

이제 구독이 디지털 지갑에서 직접 연결되는 조직을 업데이트할 수 있습니다.



==== Cloud Volume ONTAP 라이센스 관리

이제 홈 페이지 또는 * Direct licenses * 탭을 통해 Cloud Volumes ONTAP 라이센스를 관리할 수 있습니다. 마켓플레이스 구독 * 탭을 사용하여 구독 정보를 봅니다.



=== 2024년 3월 5일



==== BlueXP 재해 복구

BlueXP 디지털 지갑을 통해 이제 BlueXP 재해 복구용 라이센스를 관리할 수 있습니다. 라이센스를 추가하고 라이센스를 업데이트하며 라이센스 용량에 대한 세부 정보를 볼 수 있습니다.

https://docs.netapp.com/us-en/bluexp-digital-wallet/task-manage-data-services-licenses.html["BlueXP 데이터 서비스용 라이센스를 관리하는 방법에 관해 알아보십시오"]



=== 2023년 7월 30일



==== 사용 보고서 기능 향상

이제 Cloud Volumes ONTAP 사용 보고서의 몇 가지 개선 사항이 있습니다.

* 이제 TiB 단위는 컬럼 이름에 포함됩니다.
* 이제 일련 번호에 대한 new_node_field가 포함됩니다.
* 이제 Storage VMs Usage 보고서에 new_Workload Type_column이 포함됩니다.
* 이제 작업 환경 이름이 스토리지 VM 및 볼륨 사용 보고서에 포함됩니다.
* 이제 볼륨 type_file_은 _Primary(읽기/쓰기)_로 레이블이 지정됩니다.
* 이제 볼륨 type_secondary_이(가) _Secondary(DP)_로 표시됩니다.


사용 현황 보고서에 대한 자세한 내용은 을 참조하십시오 https://docs.netapp.com/us-en/bluexp-digital-wallet/task-manage-capacity-licenses.html#download-usage-reports["사용 보고서를 다운로드합니다"].



== 재해 복구



=== 2025년 5월 13일

버전 4.2.3



==== 서브넷 매핑

이 릴리즈에서는 각 vCenter에 대해 서브넷을 추가할 수 있는 서브넷 매핑을 사용하여 새로운 방식으로 페일오버 시 IP 주소를 관리할 수 있습니다. 이 경우 IPv4 CIDR, 기본 게이트웨이 및 각 가상 네트워크에 대한 DNS를 정의합니다.

장애 조치 시 BlueXP  재해 복구는 매핑된 가상 네트워크에 제공된 CIDR을 확인하여 각 vNIC의 적절한 IP 주소를 결정하고 이를 사용하여 새 IP 주소를 파생시킵니다.

예를 들면 다음과 같습니다.

* NetworkA = 10.1.1.0/24
* NetworkB = 192.168.1.0/24


VM1에는 NetworkA에 연결된 vNIC(10.1.1.50)가 있습니다. NetworkA는 복제 계획 설정에서 NetworkB에 매핑됩니다.

장애 조치 시 BlueXP  재해 복구는 원래 IP 주소의 네트워크 부분(10.1.1)을 대체하고 원래 IP 주소(10.1.1.50)의 호스트 주소(.50)를 유지합니다. VM1의 경우 BlueXP  재해 복구는 NetworkB에 대한 CIDR 설정을 확인하고 NetworkB 네트워크 부분 192.168.1을 사용하는 동안 호스트 부분(.50)을 유지하여 VM1에 대한 새 IP 주소를 만듭니다. 새 IP는 192.168.1.50이 됩니다.

요약하면 호스트 주소는 동일하게 유지되지만 네트워크 주소는 사이트 서브넷 매핑에 구성된 것으로 대체됩니다. 따라서 페일오버 시 IP 주소 재할당을 보다 쉽게 관리할 수 있습니다. 특히 수백 개의 네트워크와 수천 개의 VM을 관리할 수 있는 경우 더욱 그렇습니다.

사이트에서 서브넷 매핑을 포함하는 방법에 대한 자세한 내용은 을 https://docs.netapp.com/us-en/bluexp-disaster-recovery/use/sites-add.html["vCenter 서버 사이트를 추가합니다"]참조하십시오.



==== 보호를 건너뜁니다

이제 복제 계획 페일오버 후 서비스가 역방향 보호 관계를 자동으로 생성하지 않도록 보호를 건너뛸 수 있습니다. 이 기능은 복원된 사이트를 BlueXP  재해 복구 내에서 다시 온라인으로 전환하기 전에 해당 사이트에서 추가 작업을 수행하려는 경우에 유용합니다.

페일오버를 시작할 때 원래 소스 사이트가 온라인 상태인 경우 기본적으로 복제 계획의 각 볼륨에 대한 역방향 보호 관계가 자동으로 생성됩니다. 즉, 서비스가 타겟 사이트에서 소스 사이트로 다시 SnapMirror 관계를 생성합니다. 이 서비스는 페일백을 시작할 때 SnapMirror 관계도 자동으로 반전시킵니다.

이제 대체 작동을 시작할 때 * 보호 건너뛰기 * 옵션을 선택할 수 있습니다. 이 옵션을 사용하면 서비스에서 SnapMirror 관계를 자동으로 되돌리지 않습니다. 대신 쓰기 가능한 볼륨을 복제 계획의 양쪽에 남겨 둡니다.

원래 소스 사이트가 다시 온라인 상태가 되면 Replication Plan Actions 메뉴에서 * Protect resources * 를 선택하여 역방향 보호를 설정할 수 있습니다. 이렇게 하면 계획의 각 볼륨에 대한 역방향 복제 관계가 생성됩니다. 보호가 복원될 때까지 이 작업을 반복해서 실행할 수 있습니다. 보호가 복원되면 일반적인 방법으로 페일백을 시작할 수 있습니다.

건너뛰는 보호에 대한 자세한 내용은 을 https://docs.netapp.com/us-en/bluexp-disaster-recovery/use/failover.html["애플리케이션을 원격 사이트로 페일오버합니다"]참조하십시오.



==== 복제 계획에서 SnapMirror 스케줄 업데이트

이제 BlueXP  재해 복구는 기본 ONTAP SnapMirror 정책 스케줄러나 ONTAP와의 타사 통합 같은 외부 스냅샷 관리 솔루션의 사용을 지원합니다. 복제 계획의 모든 데이터 저장소(볼륨)에 이미 다른 곳에서 관리되고 있는 SnapMirror 관계가 있는 경우 이러한 스냅샷을 BlueXP  재해 복구의 복구 지점으로 사용할 수 있습니다.

구성하려면 복제 계획 > 리소스 매핑 섹션에서 데이터 저장소 매핑을 구성할 때 * 플랫폼 관리 백업 및 보존 일정 사용 * 확인란을 선택합니다.

이 옵션을 선택하면 BlueXP  재해 복구에서 백업 일정을 구성하지 않습니다. 그러나 테스트, 페일오버 및 페일백 작업을 위해 스냅샷을 계속 사용할 수 있으므로 보존 일정을 구성해야 합니다.

이 구성이 완료되면 서비스가 정기적으로 예약된 스냅샷을 만들지 않고 대신 외부 엔티티에 의존하여 해당 스냅샷을 생성하고 업데이트합니다.

복제 계획에서 외부 스냅샷 솔루션을 사용하는 방법에 대한 자세한 내용은 을 https://docs.netapp.com/us-en/bluexp-disaster-recovery/use/drplan-create.html["복제 계획을 생성합니다"]참조하십시오.



=== 2025년 4월 16일

버전 4.2.2



==== VM에 대한 검색을 예약합니다

BlueXP  재해 복구는 24시간마다 한 번씩 검색을 수행합니다. 이번 릴리스에서는 요구 사항에 맞게 검색 일정을 사용자 지정하고 필요할 때 성능에 미치는 영향을 줄일 수 있습니다. 예를 들어 VM 수가 많은 경우 검색 일정을 48시간마다 실행하도록 설정할 수 있습니다. VM 수가 적은 경우 12시간마다 실행되도록 검색 일정을 설정할 수 있습니다.

검색을 예약하기 위해 WAN을 사용하지 않는 경우 예약된 검색 옵션을 비활성화하고 언제든지 수동으로 검색을 새로 고칠 수 있습니다.

자세한 내용은 을 https://docs.netapp.com/us-en/bluexp-disaster-recovery/use/sites-add.html["vCenter 서버 사이트를 추가합니다"]참조하십시오.



==== 리소스 그룹 데이터 저장소가 지원됩니다

이전에는 VM별로 리소스 그룹을 생성할 수 있었습니다. 이번 릴리즈에서는 데이터 저장소별로 리소스 그룹을 생성할 수 있습니다. 복제 계획을 생성하고 해당 계획에 대한 리소스 그룹을 생성하는 경우 데이터 저장소의 모든 VM이 나열됩니다. 이 기능은 VM이 많은 경우 데이터 저장소를 기준으로 그룹화하려는 경우에 유용합니다.

다음과 같은 방법으로 데이터 저장소가 있는 리소스 그룹을 생성할 수 있습니다.

* 데이터 저장소를 사용하여 리소스 그룹을 추가할 때 데이터 저장소 목록을 볼 수 있습니다. 하나 이상의 데이터 저장소를 선택하여 리소스 그룹을 생성할 수 있습니다.
* 복제 계획을 만들고 계획 내에서 리소스 그룹을 만드는 경우 데이터 저장소의 VM을 볼 수 있습니다.


자세한 내용은 을 https://docs.netapp.com/us-en/bluexp-disaster-recovery/use/drplan-create.html["복제 계획을 생성합니다"]참조하십시오.



==== 무료 평가판 또는 라이센스 만료 알림

이 릴리스는 무료 평가판이 라이센스를 취득할 수 있도록 60일 후에 만료된다는 알림을 제공합니다. 이 릴리스에서는 라이센스가 만료되는 날짜에 알림을 제공합니다.



==== 서비스 업데이트 알림

이 릴리스에서는 서비스가 업그레이드되고 서비스가 유지 관리 모드로 전환되었음을 나타내는 배너가 맨 위에 표시됩니다. 서비스가 업그레이드되면 배너가 나타나고 업그레이드가 완료되면 사라집니다. 업그레이드가 진행되는 동안 UI에서 계속 작업할 수 있지만 새 작업을 제출할 수는 없습니다. 업데이트가 완료되면 예약된 작업이 실행되고 서비스가 운영 모드로 돌아갑니다.



=== 2025년 3월 10일

버전 4.2.1



==== 지능형 프록시 지원

BlueXP  커넥터는 지능형 프록시를 지원합니다. 지능형 프록시는 온프레미스 환경을 BlueXP  서비스에 연결하는 가볍고 안전하며 효율적인 방법입니다. VPN 또는 직접 인터넷 액세스 없이도 사용자 환경과 BlueXP  서비스 간에 보안 연결을 제공합니다. 이렇게 최적화된 프록시 구현은 로컬 네트워크 내에서 API 트래픽을 오프로드합니다.

프록시가 구성된 경우 BlueXP  재해 복구는 VMware 또는 ONTAP와 직접 통신을 시도하고 직접 통신이 실패할 경우 구성된 프록시를 사용합니다.

BlueXP  재해 복구 프록시를 구현하려면 HTTPS 프로토콜을 사용하여 커넥터와 vCenter Server 및 ONTAP 어레이 간에 포트 443 통신이 필요합니다. 커넥터 내의 BlueXP  재해 복구 에이전트는 작업을 수행할 때 VMware vSphere, VC 또는 ONTAP와 직접 통신합니다.

BlueXP  재해 복구용 지능형 프록시에 대한 자세한 내용은 을 참조하십시오 https://docs.netapp.com/us-en/bluexp-disaster-recovery/get-started/dr-setup.html["BlueXP 재해 복구를 위한 인프라 설정"].

BlueXP 에서 설정하는 일반 프록시에 대한 자세한 내용은 을 참조하십시오 https://docs.netapp.com/us-en/bluexp-setup-admin/task-configuring-proxy.html["프록시 서버를 사용하도록 Connector를 구성합니다"^].



==== 무료 평가판을 언제든지 종료합니다

당신은 어떤 갈래 또는 당신은 그것이 만료될 때까지 기다릴 수 무료 평가판을 중지할 수 있습니다.

을 https://docs.netapp.com/us-en/bluexp-disaster-recovery/get-started/dr-licensing.html#end-the-free-trial["무료 평가판을 종료합니다"]참조하십시오.



=== 2025년 2월 19일

버전 4.2



==== ASA R2는 VMFS 스토리지의 VM 및 데이터 저장소를 지원합니다

이번 BlueXP  재해 복구 릴리즈는 VMFS 스토리지의 VM 및 데이터 저장소용 ASA R2를 지원합니다. ASA R2 시스템에서 ONTAP 소프트웨어는 필수 SAN 기능을 지원하는 동시에 SAN 환경에서 지원되지 않는 기능을 제거합니다.

이 릴리즈에서는 ASA R2에 대해 다음 기능을 지원합니다.

* 운영 스토리지에 대한 정합성 보장 그룹 프로비저닝(플랫 정합성 보장 그룹만 해당, 즉 계층 구조가 없는 한 레벨만 해당)
* SnapMirror 자동화를 포함한 백업(일관성 그룹) 작업


BlueXP  재해 복구에서 ASA R2에 대한 지원은 ONTAP 9.16.1을 사용합니다.

데이터 저장소는 ONTAP 볼륨 또는 ASA R2 스토리지 유닛에 마운트할 수 있지만 BlueXP  재해 복구의 리소스 그룹에 ONTAP의 데이터 저장소와 ASA R2의 데이터 저장소를 모두 포함할 수는 없습니다. ONTAP에서 데이터 저장소를 선택하거나 리소스 그룹의 ASA R2에서 데이터 저장소를 선택할 수 있습니다.



=== 2024년 10월 30일



==== 보고

이제 보고서를 생성하고 다운로드하여 환경 분석에 도움을 줄 수 있습니다. 사전 설계된 보고서는 페일오버와 장애 복구를 요약하고, 모든 사이트에 대한 복제 세부 정보를 표시하며, 지난 7일 동안의 작업 세부 정보를 표시합니다.

을 https://docs.netapp.com/us-en/bluexp-disaster-recovery/use/reports.html["재해 복구 보고서를 생성합니다"]참조하십시오.



==== 30일 무료 평가판

이제 BlueXP  재해 복구의 30일 무료 평가판에 등록할 수 있습니다. 이전에는 무료 평가판이 90일이었습니다.

을 https://docs.netapp.com/us-en/bluexp-disaster-recovery/get-started/dr-licensing.html["라이센스를 설정합니다"]참조하십시오.



==== 복제 계획 해제 및 설정

이전 릴리스에는 매일 및 매주 일정을 지원하는 데 필요한 페일오버 테스트 일정 구조의 업데이트가 포함되었습니다. 이 업데이트를 수행하려면 새로운 일별 및 주별 페일오버 테스트 일정을 사용할 수 있도록 모든 기존 복제 계획을 비활성화했다가 다시 활성화해야 합니다. 이는 일회성 요구 사항입니다.

방법은 다음과 같습니다.

. 상단 메뉴에서 * Replication Plans * 를 선택합니다.
. 계획을 선택하고 조치 아이콘을 선택하여 드롭다운 메뉴를 표시합니다.
. 비활성화 * 를 선택합니다.
. 몇 분 후 * 활성화 * 를 선택합니다.




==== 폴더 매핑

복제 계획을 생성하고 컴퓨팅 리소스를 매핑할 때 데이터 센터, 클러스터 및 호스트에 대해 지정한 폴더에서 VM이 복구되도록 폴더를 매핑할 수 있습니다.

자세한 내용은 을 https://docs.netapp.com/us-en/bluexp-disaster-recovery/use/drplan-create.html["복제 계획을 생성합니다"]참조하십시오.



==== 장애 조치, 장애 복구 및 테스트 장애 조치에 대한 VM 세부 정보를 사용할 수 있습니다

장애가 발생하여 페일오버를 시작하거나, 페일백을 수행하거나, 장애 조치를 테스트하는 경우 이제 VM의 세부 정보를 보고 다시 시작하지 않은 VM을 식별할 수 있습니다.

을 https://docs.netapp.com/us-en/bluexp-disaster-recovery/use/failover.html["애플리케이션을 원격 사이트로 페일오버합니다"]참조하십시오.



==== VM 부팅 지연(부팅 순서 순서 순서 순서 지정)

이제 복제 계획을 생성할 때 계획의 각 VM에 대해 부팅 지연을 설정할 수 있습니다. 이렇게 하면 VM이 시작되도록 순서를 설정하여 이후의 우선 순위 VM이 시작되기 전에 우선 순위 VM이 모두 실행되도록 할 수 있습니다.

자세한 내용은 을 https://docs.netapp.com/us-en/bluexp-disaster-recovery/use/drplan-create.html["복제 계획을 생성합니다"]참조하십시오.



==== VM 운영 체제 정보

복제 계획을 생성하면 이제 계획의 각 VM에 대한 운영 체제를 볼 수 있습니다. 이 기능은 리소스 그룹에서 VM을 그룹화하는 방법을 결정하는 데 유용합니다.

자세한 내용은 을 https://docs.netapp.com/us-en/bluexp-disaster-recovery/use/drplan-create.html["복제 계획을 생성합니다"]참조하십시오.



==== VM 이름 별칭

복제 계획을 생성할 때 이제 재해 복구 SIT의 VM 이름에 접두사 및 접미사를 추가할 수 있습니다. 이렇게 하면 계획에 있는 VM에 대해 보다 자세한 이름을 사용할 수 있습니다.

자세한 내용은 을 https://docs.netapp.com/us-en/bluexp-disaster-recovery/use/drplan-create.html["복제 계획을 생성합니다"]참조하십시오.



==== 이전 스냅샷을 정리합니다

지정된 보존 횟수 이상으로 더 이상 필요하지 않은 모든 스냅샷을 삭제할 수 있습니다. 스냅샷 보존 수를 낮추면 스냅샷이 시간 경과에 따라 누적될 수 있으며, 이제 스냅샷을 제거하여 공간을 확보할 수 있습니다. 요청 시 또는 복제 계획을 삭제할 때 언제든지 이 작업을 수행할 수 있습니다.

자세한 내용은 을 https://docs.netapp.com/us-en/bluexp-disaster-recovery/use/manage.html["사이트, 리소스 그룹, 복제 계획, 데이터 저장소 및 가상 머신 정보를 관리합니다"]참조하십시오.



==== 스냅샷을 조정합니다

이제 소스와 타겟 간에 동기화되지 않은 스냅샷을 조정할 수 있습니다. 이 문제는 BlueXP  재해 복구 외부에 있는 타겟에서 스냅샷이 삭제된 경우에 발생할 수 있습니다. 이 서비스는 24시간마다 소스의 스냅샷을 자동으로 삭제합니다. 그러나 필요에 따라 이 작업을 수행할 수 있습니다. 이 기능을 사용하면 모든 사이트에서 스냅샷이 일관되게 유지되도록 할 수 있습니다.

자세한 내용은 을 https://docs.netapp.com/us-en/bluexp-disaster-recovery/use/manage.html["복제 계획을 관리합니다"]참조하십시오.



== E-Series 시스템



=== 2022년 9월 18일



==== E-Series 지원

이제 BlueXP에서 E-Series 시스템을 직접 검색할 수 있습니다. E-Series 시스템에 대해 살펴보고 하이브리드 멀티 클라우드 전체의 데이터를 완벽하게 파악할 수 있습니다.



== 경제적인 효율성



=== 2024년 5월 15일



==== 비활성화된 기능

일부 BlueXP 의 경제적 효율성 기능이 일시적으로 비활성화되었습니다.

* 기술 교체
* 용량 추가




=== 2024년 3월 14일



==== 기술 업데이트 옵션

기존 자산이 있고 기술을 업데이트해야 하는지 여부를 확인하려면 BlueXP의 경제적 효율성 기술 업데이트 옵션을 사용할 수 있습니다. 현재 워크로드에 대한 간단한 평가를 검토하여 추천을 하거나 지난 90일 이내에 AutoSupport 로그를 NetApp에 보낸 경우, 이제 워크로드 시뮬레이션을 제공하여 새로운 하드웨어에서 워크로드가 어떻게 수행되는지 확인할 수 있습니다.

또한 워크로드를 추가하고 기존 워크로드를 시뮬레이션에서 제외할 수 있습니다.

이전에는 자산을 평가하고 기술 업데이트가 필요한지 여부만 파악할 수 있었습니다.

이 기능은 이제 왼쪽 탐색 창의 Tech Refresh 옵션에 포함됩니다.

에 대해 자세히 https://docs.netapp.com/us-en/bluexp-economic-efficiency/use/tech-refresh.html["기술 업데이트를 평가합니다"] 알아보십시오.



=== 2023년 11월 8일



==== 기술 교체

이번 BlueXP의 경제적 효율성 릴리즈에는 자산을 평가하고 기술 업데이트가 권장되는지 여부를 확인할 수 있는 새로운 옵션이 포함되어 있습니다. 이 서비스에는 왼쪽 탐색 창에 있는 새로운 기술 업데이트 옵션, 현재 워크로드와 자산을 평가할 수 있는 새 페이지, 권장사항이 있는 보고서가 포함되어 있습니다.



== 에지 캐싱

BlueXP  에지 캐싱 서비스는 2024년 8월 7일에 제거되었습니다.



== Google 클라우드 스토리지



=== 2023년 7월 10일



==== 새로운 버킷을 추가하고 BlueXP의 기존 버킷을 관리할 수 있습니다

BlueXP Canvas에서 Google Cloud Storage 버킷을 한동안 볼 수 있었습니다. 이제 BlueXP 에서 직접 새 버킷을 추가하고 기존 버켓의 속성을 변경할 수 있습니다. https://docs.netapp.com/us-en/bluexp-google-cloud-storage/task-add-gcp-bucket.html["새로운 Google Cloud Storage 버킷을 추가하는 방법을 알아보십시오"]..



== 쿠버네티스

Kubernetes 클러스터를 검색하고 관리하는 데 대한 지원이 2024년 8월 7일에 제거되었습니다.



== 마이그레이션 보고서

BlueXP  마이그레이션 보고서 서비스가 2024년 8월 7일에 제거되었습니다.



== 온프레미스 ONTAP 클러스터



=== 2024년 11월 26일



==== 전용 모드로 ASA R2 시스템을 지원합니다

이제 프라이빗 모드에서 BlueXP 를 사용할 때 NetApp ASA R2 시스템을 검색할 수 있습니다. 이 지원은 BlueXP  3.9.46 비공개 모드 릴리즈부터 사용할 수 있습니다.

* https://docs.netapp.com/us-en/asa-r2/index.html["ASA R2 시스템에 대해 자세히 알아보십시오"^]
* https://docs.netapp.com/us-en/bluexp-setup-admin/concept-modes.html["BlueXP 배포 모드에 대해 알아보십시오"^]




=== 2024년 10월 7일



==== ASA R2 시스템 지원

이제 표준 모드 또는 제한된 모드에서 BlueXP 를 사용할 때 BlueXP 에서 NetApp ASA R2 시스템을 검색할 수 있습니다. NetApp ASA R2 시스템을 검색하고 작업 환경을 열면 바로 System Manager로 이동합니다.

ASA R2 시스템에서는 다른 관리 옵션을 사용할 수 없습니다. 표준 보기를 사용할 수 없으며 BlueXP 서비스를 활성화할 수 없습니다.

ASA R2 시스템 검색은 전용 모드에서 BlueXP 를 사용할 때 지원되지 않습니다.

* https://docs.netapp.com/us-en/asa-r2/index.html["ASA R2 시스템에 대해 자세히 알아보십시오"^]
* https://docs.netapp.com/us-en/bluexp-setup-admin/concept-modes.html["BlueXP 배포 모드에 대해 알아보십시오"^]




=== 2024년 4월 22일



==== 볼륨 템플릿은 더 이상 지원되지 않습니다

더 이상 템플릿에서 볼륨을 생성할 수 없습니다. 이 작업은 BlueXP 해결 서비스와 연계되었으며, 더 이상 사용할 수 없습니다.



== 운영 복원력



=== 2023년 4월 2일



==== BlueXP  운영 복원력 서비스

새로운 BlueXP 운영 복구 서비스와 IT 운영 위험 개선 자동화 제안을 사용하면 운영 중단이나 장애가 발생하기 전에 권장 조치를 구현할 수 있습니다.

운영 복원력 은 서비스 및 솔루션의 상태, 가동 시간, 성능을 유지하기 위해 경고 및 이벤트를 분석하는 데 도움이 되는 서비스입니다.

link:https://docs.netapp.com/us-en/bluexp-operational-resiliency/get-started/intro.html["BlueXP 운영 복원성에 대해 자세히 알아보십시오"].



== 랜섬웨어 보호



=== 2025년 4월 29일



==== NetApp ONTAP용 Amazon FSx 지원

이 릴리즈는 Amazon FSx for NetApp ONTAP을 지원합니다. 이 기능은 BlueXP  랜섬웨어 방어 기능으로 FSx for ONTAP 워크로드를 보호하는 데 도움이 됩니다.

FSx for ONTAP은 클라우드에서 NetApp ONTAP 스토리지의 강력한 기능을 제공하는 완전 관리형 서비스입니다. 또한 네이티브 AWS 서비스의 민첩성 및 확장성과 함께 사내에서 사용하는 것과 동일한 기능, 성능, 관리 기능을 제공합니다.

BlueXP  랜섬웨어 방어 워크플로우가 다음과 같이 변경되었습니다.

* 검색 기능에는 FSx for ONTAP 9.15 작업 환경의 워크로드가 포함됩니다.
* 보호 탭에는 FSx for ONTAP 환경의 워크로드가 표시됩니다. 이 환경에서는 FSx for ONTAP 백업 서비스를 사용하여 백업 작업을 수행해야 합니다. BlueXP  랜섬웨어 방지 스냅샷을 사용하여 이러한 워크로드를 복원할 수 있습니다.
+

TIP: FSx for ONTAP에서 실행되는 워크로드의 백업 정책을 BlueXP 에서 설정할 수 없습니다. Amazon FSx for NetApp ONTAP에서 설정된 기존 백업 정책은 변경되지 않고 그대로 유지됩니다.

* 경고 인시던트에는 새로운 FSx for ONTAP 작업 환경이 표시됩니다.


자세한 내용은 을 https://docs.netapp.com/us-en/bluexp-ransomware-protection/concept-ransomware-protection.html["BlueXP  랜섬웨어 방지 및 작업 환경에 대해 알아보십시오"]참조하십시오.

지원되는 옵션에 대한 자세한 내용은 를 https://docs.netapp.com/us-en/bluexp-ransomware-protection/rp-reference-limitations.html["BlueXP  랜섬웨어 방지 제한 사항"]참조하십시오.



=== 2025년 4월 14일



==== 준비 훈련 보고서

이번 릴리즈에서는 랜섬웨어 공격 준비도 훈련 보고서를 검토할 수 있습니다. 준비도 드릴을 사용하여 새로 생성된 샘플 워크로드에 대한 랜섬웨어 공격을 시뮬레이션할 수 있습니다. 그런 다음 시뮬레이션된 공격을 조사하고 샘플 워크로드를 복구합니다. 이 기능은 알림, 응답 및 복구 프로세스를 테스트하여 실제 랜섬웨어 공격이 발생했을 때 적절한 준비가 되어 있는지 파악하는 데 도움이 됩니다.

자세한 내용은 을 https://docs.netapp.com/us-en/bluexp-ransomware-protection/rp-start-simulate.html["랜섬웨어 공격 준비도 훈련을 실시합니다"]참조하십시오.



==== 새로운 역할 기반 액세스 제어 역할 및 권한

이전에는 자신의 책임에 따라 사용자에게 역할과 권한을 할당함으로써 BlueXP  랜섬웨어 방어에 대한 사용자 액세스를 관리하는 데 도움이 될 수 있었습니다. 이 릴리즈에서는 업데이트된 권한이 있는 BlueXP  랜섬웨어 보호와 관련된 두 가지 새로운 역할이 있습니다. 새로운 역할은 다음과 같습니다.

* 랜섬웨어 차단 관리자
* 랜섬웨어 방어 뷰어


사용 권한에 대한 자세한 내용은 을 https://docs.netapp.com/us-en/bluexp-ransomware-protection/rp-reference-roles.html["기능에 대한 BlueXP  랜섬웨어 방지 역할 기반 액세스"]참조하십시오.



==== 지불 개선

이 릴리스에는 결제 프로세스에 대한 몇 가지 개선 사항이 포함되어 있습니다.

자세한 내용은 을 https://docs.netapp.com/us-en/bluexp-ransomware-protection/rp-start-licenses.html["라이선스 및 결제 옵션을 설정합니다"]참조하십시오.



=== 2025년 3월 10일



==== 공격을 시뮬레이션하고 대응합니다

이 릴리즈에서는 랜섬웨어 공격을 시뮬레이션하여 랜섬웨어 경고에 대한 응답을 테스트하십시오. 이 기능은 알림, 응답 및 복구 프로세스를 테스트하여 실제 랜섬웨어 공격이 발생했을 때 적절한 준비가 되어 있는지 파악하는 데 도움이 됩니다.

자세한 내용은 을 https://docs.netapp.com/us-en/bluexp-ransomware-protection/rp-start-simulate.html["랜섬웨어 공격 준비도 훈련을 실시합니다"]참조하십시오.



==== 검색 프로세스 개선

이 릴리스에는 선택적 검색 및 재검색 프로세스의 향상된 기능이 포함되어 있습니다.

* 이 릴리즈를 사용하면 이전에 선택한 작업 환경에 추가된 새로 생성된 워크로드를 검색할 수 있습니다.
* 이 릴리스에서는 _NEW_WORKING 환경을 선택할 수도 있습니다. 이 기능을 사용하면 환경에 추가되는 새 워크로드를 보호할 수 있습니다.
* 검색 프로세스 초기에 또는 설정 옵션에서 이러한 검색 프로세스를 수행할 수 있습니다.


자세한 https://docs.netapp.com/us-en/bluexp-ransomware-protection/rp-start-discover.html["이전에 선택한 작업 환경에 대해 새로 생성된 워크로드를 검색합니다"] 내용은 및 https://docs.netapp.com/us-en/bluexp-ransomware-protection/rp-use-settings.html["설정 옵션을 사용하여 기능을 구성합니다"]을 참조하십시오.



==== 높은 암호화가 감지될 때 경고가 발생합니다

이 릴리스에서는 높은 파일 확장명을 변경하지 않고도 작업 부하에서 높은 암호화가 감지될 때 알림을 볼 수 있습니다. ONTAP ARP(자율적 랜섬웨어 방어) AI를 사용하는 이 기능은 랜섬웨어 공격의 위험이 있는 워크로드를 파악하는 데 도움이 됩니다. 이 기능을 사용하여 확장자 변경 여부에 관계없이 영향을 받는 파일의 전체 목록을 다운로드합니다.

자세한 내용은 을 https://docs.netapp.com/us-en/bluexp-ransomware-protection/rp-use-alert.html["감지된 랜섬웨어 경고에 대응합니다"]참조하십시오.



=== 2024년 12월 16일



==== Data Infrastructure Insights 스토리지 워크로드 보안을 사용하여 비정상적인 사용자 행동을 감지합니다

이 릴리즈에서는 Data Infrastructure Insights 스토리지 워크로드 보안을 사용하여 스토리지 워크로드에서 비정상적인 사용자 행동을 감지할 수 있습니다. 이 기능을 사용하면 잠재적 보안 위협을 식별하고 악의적인 사용자를 차단하여 데이터를 보호할 수 있습니다.

자세한 내용은 을 https://docs.netapp.com/us-en/bluexp-ransomware-protection/rp-use-alert.html["감지된 랜섬웨어 경고에 대응합니다"]참조하십시오.

데이터 인프라 인사이트 스토리지 워크로드 보안을 사용하여 비정상적인 사용자 행동을 감지하기 전에 BlueXP  랜섬웨어 방지 * 설정 * 옵션을 사용하여 옵션을 구성해야 합니다.

을 https://docs.netapp.com/us-en/bluexp-ransomware-protection/rp-use-settings.html["BlueXP 랜섬웨어 보호 설정을 구성합니다"]참조하십시오.



==== 검색하고 보호할 워크로드를 선택하십시오

이 릴리스에서는 이제 다음을 수행할 수 있습니다.

* 각 커넥터 내에서 워크로드를 검색할 작업 환경을 선택합니다. 사용자 환경에서 특정 워크로드를 보호하려는 경우 이 기능을 유용하게 사용할 수 있습니다.
* 워크로드 검색 중에 커넥터별 워크로드를 자동으로 검색할 수 있습니다. 이 기능을 통해 보호할 워크로드를 선택할 수 있습니다.
* 이전에 선택한 작업 환경에 대해 새로 생성된 워크로드를 검색합니다.


을 https://docs.netapp.com/us-en/bluexp-ransomware-protection/rp-start-discover.html["워크로드 검색"]참조하십시오.



== 해결

BlueXP 개선 서비스가 2024년 4월 22일에 제거되었습니다.



== 복제



=== 2022년 9월 18일



==== ONTAP에서 Cloud Volumes ONTAP로 FSX

이제 ONTAP 파일 시스템용 Amazon FSx에서 Cloud Volumes ONTAP로 데이터를 복제할 수 있습니다.

https://docs.netapp.com/us-en/bluexp-replication/task-replicating-data.html["데이터 복제를 설정하는 방법에 대해 알아보십시오"].



=== 2022년 7월 31일



==== ONTAP용 FSX를 데이터 소스로 사용합니다

이제 Amazon FSx for ONTAP 파일 시스템에서 다음 대상으로 데이터를 복제할 수 있습니다.

* ONTAP용 Amazon FSx
* 사내 ONTAP 클러스터


https://docs.netapp.com/us-en/bluexp-replication/task-replicating-data.html["데이터 복제를 설정하는 방법에 대해 알아보십시오"].



=== 2021년 9월 2일



==== ONTAP용 Amazon FSx 지원

이제 Cloud Volumes ONTAP 시스템 또는 온프레미스 ONTAP 클러스터에서 ONTAP 파일 시스템용 Amazon FSx로 데이터를 복제할 수 있습니다.

https://docs.netapp.com/us-en/bluexp-replication/task-replicating-data.html["데이터 복제를 설정하는 방법에 대해 알아보십시오"].



== 소프트웨어 업데이트



=== 2025년 4월 2일



==== 위험 완화

이제 BlueXP  소프트웨어 업데이트의 요약 섹션에서 운영 체제 업데이트로 완화할 수 있는 총 위험 수를 볼 수 있습니다. 이를 통해 사용자는 설치 기반에서 보안 및 안정성 향상을 평가할 수 있습니다.



=== 2024년 8월 7일



==== ONTAP 업데이트

BlueXP  소프트웨어 업데이트 서비스는 위험을 완화하고 고객이 ONTAP 기능을 최대한 활용할 수 있도록 함으로써 사용자에게 원활한 업데이트 환경을 제공합니다.

에 대해 자세히 link:https://docs.netapp.com/us-en/bluexp-software-updates/get-started/software-updates.html["BlueXP  소프트웨어 업데이트"]알아보십시오.



== StorageGRID



=== 2024년 8월 7일



==== 새로운 고급 보기

StorageGRID 11.8부터 친숙한 그리드 관리자 인터페이스를 사용하여 BlueXP 에서 StorageGRID 시스템을 관리할 수 있습니다.

https://docs.netapp.com/us-en/bluexp-storagegrid/task-administer-storagegrid.html["고급 보기를 사용하여 StorageGRID를 관리하는 방법에 대해 알아봅니다"]..



==== StorageGRID 관리 인터페이스 인증서를 검토하고 승인할 수 있습니다

이제 BlueXP 에서 StorageGRID 시스템을 검색할 때 StorageGRID 관리 인터페이스 인증서를 검토하고 승인할 수 있습니다. 검색된 그리드에서 최신 StorageGRID 관리 인터페이스 인증서를 검토하고 승인할 수도 있습니다.

https://docs.netapp.com/us-en/bluexp-storagegrid/task-discover-storagegrid.html["시스템 검색 중에 서버 인증서를 검토하고 승인하는 방법에 대해 알아봅니다."]



=== 2022년 9월 18일



==== StorageGRID 지원

이제 BlueXP에서 직접 StorageGRID 시스템을 검색할 수 있습니다. StorageGRID을 발견하여 하이브리드 멀티 클라우드 전체의 데이터를 완벽하게 파악할 수 있습니다.



== 계층화



=== 2023년 8월 9일



==== 버킷 이름에 사용자 지정 접두사를 사용합니다

이전에는 버킷 이름을 정의할 때 기본 "fabric-pool" 접두사를 사용해야 했습니다(예: _fabric-pool-bucket1_). 이제 버킷 이름을 지정할 때 사용자 지정 접두사를 사용할 수 있습니다. 이 기능은 데이터를 Amazon S3로 계층화하는 경우에만 사용할 수 있습니다. https://docs.netapp.com/us-en/bluexp-tiering/task-tiering-onprem-aws.html#prepare-your-aws-environment["자세한 정보"].



==== 모든 BlueXP Connector에서 클러스터를 검색합니다

사용자 환경의 모든 스토리지 시스템을 관리하기 위해 여러 커넥터를 사용하는 경우 계층화를 구현할 클러스터가 다른 커넥터에 있을 수 있습니다. 어떤 커넥터가 특정 클러스터를 관리하고 있는지 확실하지 않은 경우 BlueXP 계층화를 사용하여 모든 커넥터를 검색할 수 있습니다. https://docs.netapp.com/us-en/bluexp-tiering/task-managing-tiering.html#search-for-a-cluster-across-all-bluexp-connectors["자세한 정보"].



=== 2023년 7월 4일



==== 대역폭을 조정하여 비활성 데이터를 전송합니다

BlueXP 계층화를 활성화하면 ONTAP는 무제한의 네트워크 대역폭을 사용하여 클러스터의 볼륨에서 객체 스토리지로 비활성 데이터를 전송할 수 있습니다. 계층화 트래픽이 정상적인 사용자 워크로드에 영향을 미치는 경우 전송 중에 사용할 수 있는 대역폭의 양을 조절할 수 있습니다. https://docs.netapp.com/us-en/bluexp-tiering/task-managing-tiering.html#changing-the-network-bandwidth-available-to-upload-inactive-data-to-object-storage["자세한 정보"]..



==== 알림 센터에 계층화 이벤트가 표시됩니다

계층화 이벤트 "Tier additional data from cluster <name> to object storage to increase storage Efficiency"는 이제 클러스터가 데이터를 계층화하는 경우를 포함하여 콜드 데이터의 20% 미만을 계층화할 때 알림으로 표시됩니다.

이 알림은 시스템의 효율성을 높이고 스토리지 비용을 절감하는 데 도움이 되는 "권장 사항"입니다. 에 대한 링크를 제공합니다 https://bluexp.netapp.com/cloud-tiering-service-tco["BlueXP 계층화 총 소유 비용 및 절감 계산기"^] 비용 절감 효과를 계산하는 데 도움이 됩니다.



=== 2023년 4월 3일



==== 라이센스 탭이 제거되었습니다

BlueXP 계층화 인터페이스에서 라이센스 탭이 제거되었습니다. PAYGO(pay-as-you-go) 서브스크립션에 대한 모든 라이센스는 이제 BlueXP 계층화 온-프레미스 대시보드에서 액세스할 수 있습니다. 또한 BlueXP 계층화 기능을 통해 BYOL(Bring-Your-Own-License)을 확인하고 관리할 수 있도록 해당 페이지에서 BlueXP 디지털 지갑까지 연결되는 링크도 있습니다.



==== 계층화 탭의 이름이 변경되고 업데이트되었습니다

"클러스터 대시보드" 탭의 이름이 "클러스터"로 바뀌고 "온프레미스 개요" 탭의 이름이 "온-프레미스 대시보드"로 바뀌었습니다. 이러한 페이지에는 추가 계층화 구성으로 스토리지 공간을 최적화할 수 있는지 평가하는 데 도움이 되는 몇 가지 정보가 추가되었습니다.



== 볼륨 캐싱



=== 2023년 6월 4일



==== 볼륨 캐싱

ONTAP 9 소프트웨어의 기능인 볼륨 캐싱은 파일 배포를 간소화하고, 사용자와 컴퓨팅 리소스의 위치에 리소스를 더 가깝게 배치함으로써 WAN 대기 시간을 줄이고, WAN 대역폭 비용을 절감하는 원격 캐싱 기능입니다. 볼륨 캐싱은 원격 위치에서 쓰기 가능한 영구 볼륨을 제공합니다. BlueXP 볼륨 캐싱을 사용하여 데이터 액세스 속도를 높이거나 자주 액세스하는 볼륨에서 트래픽을 오프로드할 수 있습니다. 캐시 볼륨은 특히 클라이언트가 동일한 데이터에 반복적으로 액세스해야 하는 읽기 집약적인 워크로드에 적합합니다.

BlueXP 볼륨 캐싱을 사용하면 클라우드에 대한 캐싱 기능이 있으며, 특히 NetApp ONTAP, Cloud Volumes ONTAP 및 온-프레미스에서 작업 환경으로 사용되는 Amazon FSx를 지원합니다.

link:https://docs.netapp.com/us-en/bluexp-volume-caching/get-started/cache-intro.html["BlueXP 볼륨 캐싱에 대해 자세히 알아보십시오"].



== 워크로드 공장



=== 2025년 5월 4일



==== CloudShell 자동 지원

BlueXP  워크로드 팩토리 CloudShell을 사용하는 경우 명령 입력을 시작하고 Tab 키를 눌러 사용 가능한 옵션을 볼 수 있습니다. 가능성이 여러 개인 경우 CLI에 제안 목록이 표시됩니다. 이 기능은 오류를 최소화하고 명령 실행 속도를 높여 생산성을 향상시킵니다.



==== 사용 권한 용어가 업데이트되었습니다

워크로드 팩토리 사용자 인터페이스 및 설명서에서는 이제 "읽기 전용"을 사용하여 읽기 권한을 참조하고 "읽기-쓰기"를 사용하여 사용 권한을 자동화합니다.



=== 2025년 3월 30일



==== CloudShell은 ONTAP CLI 명령에 대한 AI에서 생성된 오류 응답을 보고합니다

CloudShell을 사용할 경우 ONTAP CLI 명령을 실행하고 오류가 발생할 때마다 실패 설명, 장애 원인, 상세한 해결 방법 등을 통해 AI에서 생성된 오류에 대한 응답을 받을 수 있습니다.

link:https://docs.netapp.com/us-en/workload-setup-admin/use-cloudshell.html["CloudShell을 사용합니다"]



==== IAM: SimulatePermissionPolicy 권한 업데이트

이제 AWS 계정 자격 증명을 추가하거나 GenAI 워크로드와 같은 새로운 워크로드 기능을 추가할 때 워크로드 팩토리 콘솔에서 권한을 관리할 수 있습니다 `iam:SimulatePrincipalPolicy`.

link:https://docs.netapp.com/us-en/workload-setup-admin/permissions-reference.html#change-log["권한 참조 변경 로그"]



=== 2025년 2월 2일



==== BlueXP  워크로드 공장 콘솔에서 사용할 수 있는 CloudShell

CloudShell은 BlueXP  워크로드 공장 콘솔의 모든 곳에서 사용할 수 있습니다. CloudShell을 사용하면 BlueXP  계정에 제공한 AWS 및 ONTAP 자격 증명을 사용하고 셸 유사 환경에서 AWS CLI 명령 또는 ONTAP CLI 명령을 실행할 수 있습니다.

link:https://docs.netapp.com/us-en/workload-setup-admin/use-cloudshell.html["CloudShell을 사용합니다"]



==== 데이터베이스에 대한 사용 권한 업데이트

이제 데이터베이스에 대해 _READ_MODE에서 다음 권한을 사용할 수 `iam:SimulatePrincipalPolicy` 있습니다.

link:https://docs.netapp.com/us-en/workload-setup-admin/permissions-reference.html#change-log["권한 참조 변경 로그"]
