---
sidebar: sidebar 
permalink: whats-new.html 
keywords: 'what"s new, features, new, release notes, enhancements, fixes, new features,cloud manager, bluexp, cloud volumes ontap, licenses, digital wallet, subscriptions, cloud backup, cloud tiering, data sense, ransomware, connector, amazon fsx for ontap, azure netapp files, cloud sync, e-series, global file cache, google cloud, disaster recovery, backup and recovery, classification, copy and sync, edge cache, edge caching, volume caching, ontap clusters, alerts, identity and access management, iam, recovery' 
summary: BlueXP 플랫폼의 일부인 클라우드 서비스의 최신 변경 사항에 대해 알아보십시오. 
---
= BlueXP의 최근 변경 사항
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
BlueXP 플랫폼의 일부인 클라우드 서비스의 최신 변경 사항에 대해 알아보십시오. 전체 릴리스 기록을 보려면 로 이동하십시오 link:release-notes-index.html["전체 릴리스 정보 세트"] 각 개별 서비스에 대해.



== 관리 기능

이 섹션에서는 계정, 커넥터, 클라우드 공급자 자격 증명 등과 같은 BlueXP 관리 기능과 관련된 새로운 기능에 대해 설명합니다.



=== 2025년 8월 11일



==== 커넥터 3.9.55

이번 BlueXP 커넥터 릴리스에는 보안 개선 및 버그 수정이 포함되어 있습니다.

3.9.55 릴리스는 표준 모드와 제한 모드에서 사용할 수 있습니다.



==== 일본어 지원

BlueXP UI가 이제 일본어로 제공됩니다. 브라우저 언어가 일본어인 경우 BlueXP 일본어로 표시됩니다. 일본어로 된 문서에 접근하려면 문서 웹사이트의 언어 메뉴를 이용하세요.



==== BlueXP  ID 및 액세스 관리(IAM)

BlueXP 의 ID 및 액세스 관리는 이제 다음 기능을 제공합니다.



==== 운영 지원을 위한 새로운 액세스 역할

BlueXP 이제 운영 지원 분석가 역할을 지원합니다. 이 역할은 사용자에게 스토리지 알림을 모니터링하고, BlueXP 감사 타임라인을 보고, NetApp 지원 사례를 입력 및 추적할 수 있는 권한을 부여합니다.

link:https://docs.netapp.com/us-en/bluexp-setup-admin/reference-iam-predefined-roles.html["액세스 역할 사용에 대해 자세히 알아보세요."]



=== 2025년 7월 31일



==== 프라이빗 모드 출시 (3.9.54)

이제 에서 새 비공개 모드 릴리스를 다운로드할 수 있습니다 https://mysupport.netapp.com/site/downloads["NetApp Support 사이트"^]

3.9.54 릴리스에는 다음 BlueXP 구성 요소와 서비스에 대한 업데이트가 포함되어 있습니다.

[cols="3*"]
|===
| 구성 요소 또는 서비스 | 이 릴리스에 포함된 버전입니다 | 이전 비공개 모드 릴리스 이후 변경된 사항입니다 


| 커넥터 | 3.9.54, 3.9.53 | 로 가다 https://docs.netapp.com/us-en/bluexp-setup-admin/whats-new.html#connector-3-9-50["BlueXP 페이지의 새로운 소식"^] 버전 3.9.54 및 3.9.53에 포함된 변경 사항을 참조하세요. 


| 백업 및 복구 | 2025년 7월 28일 | 로 가다 https://docs.netapp.com/us-en/bluexp-backup-recovery/whats-new.html["BlueXP  백업 및 복구 페이지의 새로운 기능"^] 2025년 7월 릴리스에 포함된 변경 사항을 참조하세요. 


| 분류 | 2025년 7월 14일(버전 1.45) | 로 가다 https://docs.netapp.com/us-en/bluexp-classification/whats-new.html["BlueXP  분류 페이지의 새로운 기능"^] . 
|===
업그레이드 방법을 포함하여 개인 모드에 대한 자세한 내용은 다음을 참조하십시오.

* https://docs.netapp.com/us-en/bluexp-setup-admin/concept-modes.html["비공개 모드에 대해 알아봅니다"]
* https://docs.netapp.com/us-en/bluexp-setup-admin/task-quick-start-private-mode.html["프라이빗 모드에서 BlueXP를 시작하는 방법을 알아보십시오"]
* https://docs.netapp.com/us-en/bluexp-setup-admin/task-upgrade-connector.html["비공개 모드를 사용할 때 커넥터를 업그레이드하는 방법에 대해 알아봅니다"]




=== 2025년 7월 21일



==== Google Cloud NetApp Volumes 지원

이제 BlueXP 에서 Google Cloud NetApp Volumes 볼 수 있습니다.link:https://docs.netapp.com/us-en//bluexp-google-cloud-netapp-volumes/index.html["Google Cloud NetApp Volumes 에 대해 자세히 알아보세요."]



==== BlueXP  ID 및 액세스 관리(IAM)



===== Google Cloud NetApp Volumes 에 대한 새로운 액세스 역할

BlueXP 이제 다음 스토리지 시스템에 대한 액세스 역할 사용을 지원합니다.

* Google Cloud NetApp 볼륨


link:https://docs.netapp.com/us-en/bluexp-setup-admin/reference-iam-predefined-roles.html["액세스 역할 사용에 대해 자세히 알아보세요."]



=== 2025년 7월 14일



==== 커넥터 3.9.54

BlueXP 커넥터의 이번 릴리스에는 보안 개선, 버그 수정 및 다음과 같은 새로운 기능이 포함되어 있습니다.

* Cloud Volumes ONTAP 서비스를 지원하는 커넥터에 대한 투명 프록시 지원. link:https://docs.netapp.com/us-en/bluexp-setup-admin/task-configuring-proxy.html["투명 프록시 구성에 대해 자세히 알아보세요."]
* Google Cloud 환경에 커넥터가 배포된 경우 네트워크 태그를 사용하여 커넥터 트래픽을 라우팅하는 기능입니다.
* CPU 및 RAM 사용량을 포함한 커넥터 상태 모니터링을 위한 추가 제품 내 알림입니다.


현재 3.9.54 릴리스는 표준 모드 및 제한 모드에서 사용할 수 있습니다.



==== BlueXP  ID 및 액세스 관리(IAM)

BlueXP 의 ID 및 액세스 관리 기능은 이제 다음과 같은 기능을 제공합니다.

* 개인 모드에서 IAM을 지원하여 BlueXP 서비스와 애플리케이션에 대한 사용자 액세스와 권한을 관리할 수 있습니다.
* 더 쉬운 탐색, 페더레이션 연결을 구성하기 위한 더 명확한 옵션, 기존 페더레이션에 대한 가시성 향상 등 ID 페더레이션의 관리가 간소화되었습니다.
* BlueXP backup and recovery, BlueXP disaster recovery, 페더레이션 관리에 대한 액세스 역할입니다.




===== 개인 모드에서 IAM 지원

BlueXP 이제 프라이빗 모드에서 IAM을 지원하여 BlueXP 서비스 및 애플리케이션의 사용자 액세스 및 권한을 관리할 수 있습니다. 이 향상된 기능을 통해 프라이빗 모드 고객은 역할 기반 액세스 제어(RBAC)를 활용하여 보안 및 규정 준수를 강화할 수 있습니다.

link:https://docs.netapp.com/us-en/bluexp-setup-admin/whats-new.html#iam["BlueXP 의 IAM에 대해 자세히 알아보세요."]



===== ID 연합의 간소화된 관리

BlueXP 이제 ID 페더레이션 관리를 위한 더욱 직관적인 인터페이스를 제공합니다. 더욱 간편한 탐색, 페더레이션 연결 구성 옵션의 명확성, 그리고 기존 페더레이션에 대한 가시성 향상이 포함됩니다.

ID 페더레이션을 통해 단일 로그인(SSO)을 활성화하면 사용자가 회사 자격 증명으로 BlueXP 에 로그인할 수 있습니다. 이를 통해 보안이 강화되고, 비밀번호 사용이 줄어들며, 온보딩이 간소화됩니다.

새로운 관리 기능에 액세스하려면 기존 페더레이션 연결을 새 인터페이스로 가져오라는 메시지가 표시됩니다. 이를 통해 페더레이션 연결을 다시 만들지 않고도 최신 개선 사항을 활용할 수 있습니다. link:https://docs.netapp.com/us-en/bluexp-setup-admin/task-federation-import.html["기존 페더레이션 연결을 BlueXP 로 가져오는 방법에 대해 자세히 알아보세요."]

개선된 페더레이션 관리를 통해 다음을 수행할 수 있습니다.

* 여러 개의 검증된 도메인을 페더레이션 연결에 추가하면 동일한 ID 공급자(IdP)를 사용하여 여러 도메인을 사용할 수 있습니다.
* 필요한 경우 페더레이션 연결을 비활성화하거나 삭제하여 사용자 액세스 및 보안을 제어할 수 있습니다.
* IAM 역할을 사용하여 페더레이션 관리에 대한 액세스를 제어합니다.


link:https://docs.netapp.com/us-en/bluexp-setup-admin/concept-federation.html["BlueXP 의 ID 페더레이션에 대해 자세히 알아보세요."]



===== BlueXP backup and recovery, BlueXP disaster recovery 및 페더레이션 관리를 위한 새로운 액세스 역할

이제 BlueXP 다음 기능과 데이터 서비스에 대해 IAM 역할을 사용할 수 있도록 지원합니다.

* BlueXP 백업 및 복구
* BlueXP 재해 복구
* 연합


link:https://docs.netapp.com/us-en/bluexp-setup-admin/reference-iam-predefined-roles.html["액세스 역할 사용에 대해 자세히 알아보세요."]



== 경고



=== 2024년 10월 7일



==== BlueXP  알림 목록 페이지

용량이 낮거나 성능이 낮은 ONTAP 클러스터를 신속하게 식별하고, 가용성 범위를 판단하며, 보안 위험을 식별할 수 있습니다. 용량, 성능, 보호, 가용성, 보안 및 구성과 관련된 경고를 볼 수 있습니다.



==== 경고 세부 정보

알림 세부 정보를 상세히 파악하고 권장 사항을 찾을 수 있습니다.



==== ONTAP System Manager에 연결된 클러스터 세부 정보를 봅니다

BlueXP  경고를 사용하면 ONTAP 스토리지 환경과 연결된 경고를 확인하고 ONTAP System Manager에 연결된 세부 정보를 드릴다운할 수 있습니다.

https://docs.netapp.com/us-en/bluexp-alerts/concept-alerts.html["BlueXP  알림에 대해 자세히 알아봅니다"]..



== ONTAP용 Amazon FSx



=== 2025년 8월 3일



==== 복제 관계 탭 개선

*복제 관계* 탭에서 복제 관계에 대한 자세한 정보를 제공하기 위해 복제 관계 표에 여러 개의 새 열을 추가했습니다. 이제 표에는 다음 열이 포함됩니다.

* SnapMirror 정책
* 소스 파일 시스템
* 대상 파일 시스템
* 관계의 상태
* 마지막 환승 시간




=== 2025년 7월 14일



==== 두 FSx for ONTAP 파일 시스템 간 데이터 복제 지원

이제 BlueXP 콘솔의 캔버스에서 두 FSx for ONTAP 파일 시스템 간에 데이터를 복제할 수 있습니다.

link:https://docs.netapp.com/us-en/bluexp-fsx-ontap/use/task-manage-working-environment.html#replicate-data["데이터 복제"]



=== 2025년 6월 29일



==== 자격 증명 업데이트

FSx for ONTAP 파일 시스템에 대한 자격 증명과 권한을 설정하면 BlueXP 자격 증명 페이지로 리디렉션됩니다. 이 페이지에서 FSx for ONTAP 자격 증명의 이름을 변경하거나 삭제할 수 있습니다.

link:https://docs.netapp.com/us-en/bluexp-fsx-ontap/requirements/task-setting-up-permissions-fsx.html["ONTAP 파일 시스템용 FSx에 대한 권한 설정"]



== Amazon S3 스토리지



=== 2023년 3월 5일



==== BlueXP에서 새 버킷을 추가할 수 있습니다

BlueXP Canvas에서 Amazon S3 버킷을 잠시 볼 수 있었습니다. 이제 BlueXP 에서 직접 새 버킷을 추가하고 기존 버켓의 속성을 변경할 수 있습니다. https://docs.netapp.com/us-en/bluexp-s3-storage/task-add-s3-bucket.html["새 Amazon S3 버킷을 추가하는 방법을 알아보십시오"]..



== Azure Blob 저장소



=== 2023년 6월 5일



==== BlueXP에서 새 스토리지 계정을 추가할 수 있습니다

BlueXP Canvas에서 Azure Blob Storage를 한동안 볼 수 있는 기능이 있습니다. 이제 BlueXP 에서 직접 새 스토리지 계정을 추가하고 기존 스토리지 계정의 속성을 변경할 수 있습니다. https://docs.netapp.com/us-en/bluexp-blob-storage/task-add-blob-storage.html["새 Azure Blob 저장소 계정을 추가하는 방법을 알아보십시오"]..



== Azure NetApp Files



=== 2025년 1월 13일



==== 이제 BlueXP 에서 네트워크 기능이 지원됩니다

BlueXP 의 Azure NetApp Files에서 볼륨을 구성할 때 이제 네트워크 기능을 지정할 수 있습니다. 이는 네이티브 Azure NetApp Files에서 제공되는 기능에 맞게 조정됩니다.



=== 2024년 6월 12일



==== 새 권한이 필요합니다

이제 BlueXP에서 Azure NetApp Files 볼륨을 관리하려면 다음 권한이 필요합니다.

Microsoft.Network/virtualNetworks/subnets/read

가상 네트워크 서브넷을 읽으려면 이 권한이 필요합니다.

현재 BlueXP에서 Azure NetApp Files를 관리하고 있는 경우 이전에 생성한 Microsoft Entra 애플리케이션과 연결된 사용자 지정 역할에 이 권한을 추가해야 합니다.

https://docs.netapp.com/us-en/bluexp-azure-netapp-files/task-set-up-azure-ad.html["Microsoft Entra 응용 프로그램을 설정하고 사용자 지정 역할 권한을 보는 방법에 대해 알아봅니다"]..



=== 2024년 4월 22일



==== 볼륨 템플릿은 더 이상 지원되지 않습니다

더 이상 템플릿에서 볼륨을 생성할 수 없습니다. 이 작업은 BlueXP 해결 서비스와 연계되었으며, 더 이상 사용할 수 없습니다.



== 백업 및 복구



=== 2025년 7월 28일

이 BlueXP  백업 및 복구 릴리스에는 다음 업데이트가 포함되어 있습니다.



==== 미리 보기로 Kubernetes 워크로드 지원

BlueXP backup and recovery 의 이번 릴리스에서는 Kubernetes 워크로드 검색 및 관리에 대한 지원이 도입되었습니다.

* kubeconfig 파일을 공유하지 않고도 NetApp ONTAP 지원하는 Red Hat OpenShift와 오픈 소스 Kubernetes 클러스터를 살펴보세요.
* 통합 제어 평면을 사용하여 여러 Kubernetes 클러스터에서 애플리케이션을 검색, 관리 및 보호합니다.
* Kubernetes 애플리케이션의 백업 및 복구를 위한 데이터 이동 작업을 NetApp ONTAP 으로 오프로드합니다.
* 로컬 및 개체 스토리지 기반 애플리케이션 백업을 조율합니다.
* 모든 Kubernetes 클러스터에 전체 애플리케이션과 개별 리소스를 백업하고 복원합니다.
* Kubernetes에서 실행되는 컨테이너와 가상 머신을 사용합니다.
* 실행 후크와 템플릿을 사용하여 애플리케이션과 일관된 백업을 만듭니다.


Kubernetes 워크로드 보호에 대한 자세한 내용은 다음을 참조하세요.  https://docs.netapp.com/us-en/bluexp-backup-recovery/br-use-kubernetes-protect-overview.html["Kubernetes 워크로드 보호 개요"] .



=== 2025년 7월 14일

이 BlueXP  백업 및 복구 릴리스에는 다음 업데이트가 포함되어 있습니다.



==== 향상된 ONTAP 볼륨 대시보드

2025년 4월, 훨씬 더 빠르고 효율적인 향상된 ONTAP 볼륨 대시보드의 미리보기를 출시했습니다.

이 대시보드는 작업량이 많은 기업 고객을 위해 설계되었습니다. 볼륨이 2만 개에 달하는 고객이라도 새 대시보드는 10초 이내에 로드됩니다.

성공적인 미리보기와 미리보기 고객 여러분의 좋은 피드백을 바탕으로, 이제 모든 고객에게 기본 환경으로 제공합니다. 눈부시게 빠른 대시보드를 경험해 보세요.

자세한 내용은 을 참조하십시오 link:br-use-dashboard.html["대시보드에서 보호 상태 보기"].



==== 공개 기술 미리 보기로서 Microsoft SQL Server 워크로드 지원

이번 BlueXP backup and recovery 릴리스는 BlueXP backup and recovery 서비스에 익숙한 3-2-1 보호 전략을 사용하여 Microsoft SQL Server 워크로드를 관리할 수 있도록 업데이트된 사용자 인터페이스를 제공합니다. 이 새로운 버전을 사용하면 이러한 워크로드를 기본 스토리지에 백업하고, 보조 스토리지에 복제하고, 클라우드 객체 스토리지에 백업할 수 있습니다.

이것을 완료하면 미리보기에 가입할 수 있습니다.  https://forms.office.com/pages/responsepage.aspx?id=oBEJS5uSFUeUS8A3RRZbOojtBW63mDRDv3ZK50MaTlJUNjdENllaVTRTVFJGSDQ2MFJIREcxN0EwQi4u&route=shorturl["미리보기 가입 양식"^] .


NOTE: Microsoft SQL Server 워크로드 보호에 대한 이 문서는 기술 미리보기 형태로 제공됩니다. NetApp 이 미리보기 버전의 제품 세부 정보, 내용 및 출시 일정을 정식 출시 전에 수정할 권리를 보유합니다.

이 버전의 BlueXP backup and recovery 다음과 같은 업데이트가 포함되어 있습니다.

* *3-2-1 백업 기능*: 이 버전은 SnapCenter 기능을 통합하여 BlueXP backup and recovery 사용자 인터페이스에서 3-2-1 데이터 보호 전략을 통해 SnapCenter 리소스를 관리하고 보호할 수 있습니다.
* * SnapCenter 에서 가져오기*: SnapCenter 백업 데이터와 정책을 BlueXP backup and recovery 로 가져올 수 있습니다.
* *재설계된 사용자 인터페이스*는 백업 및 복구 작업을 관리하는 데 있어 보다 직관적인 환경을 제공합니다.
* *백업 대상*: Amazon Web Services(AWS), Microsoft Azure Blob Storage, StorageGRID 및 ONTAP S3 환경에 버킷을 추가하여 Microsoft SQL Server 워크로드의 백업 대상으로 사용할 수 있습니다.
* *워크로드 지원*: 이 버전을 사용하면 Microsoft SQL Server 데이터베이스 및 가용성 그룹을 백업, 복원, 검증 및 복제할 수 있습니다. (다른 워크로드에 대한 지원은 향후 릴리스에서 추가될 예정입니다.)
* *유연한 복원 옵션*: 이 버전을 사용하면 데이터가 손상되거나 실수로 데이터가 손실된 경우 원래 위치와 대체 위치 모두로 데이터베이스를 복원할 수 있습니다.
* *즉각적인 프로덕션 사본*: 몇 시간 또는 며칠이 아닌 몇 분 만에 개발, 테스트 또는 분석을 위한 공간 효율적인 프로덕션 사본을 생성합니다.
* 이 버전에는 자세한 보고서를 만드는 기능이 포함되어 있습니다.


Microsoft SQL Server 작업 부하 보호에 대한 자세한 내용은 다음을 참조하세요. link:br-use-mssql-protect-overview.html["Microsoft SQL Server 워크로드 보호 개요"] .



=== 2025년 6월 9일

이 BlueXP  백업 및 복구 릴리스에는 다음 업데이트가 포함되어 있습니다.



==== 색인된 카탈로그 지원 업데이트

2025년 2월, 데이터 복원 시 검색 및 복원 방식에 사용되는 업데이트된 인덱싱 기능(인덱싱된 카탈로그 v2)이 출시되었습니다. 이전 릴리스에서는 온프레미스 환경에서 데이터 인덱싱 성능이 크게 향상되었습니다. 이번 릴리스에서는 Amazon Web Services, Microsoft Azure, Google Cloud Platform(GCP) 환경에서 인덱싱 카탈로그를 사용할 수 있습니다.

신규 고객인 경우, 모든 신규 환경에서 Indexed Catalog v2가 기본적으로 활성화됩니다. 기존 고객인 경우, Indexed Catalog v2를 활용하기 위해 기존 환경을 다시 인덱싱할 수 있습니다.

.인덱싱을 활성화하려면 어떻게 해야 합니까?
데이터를 복원하는 검색 및 복원 방법을 사용하려면 먼저 볼륨 또는 파일을 복원하려는 각 소스 작업 환경에서 "인덱싱"을 활성화해야 합니다. 검색 및 복원을 수행할 때 *인덱싱 사용* 옵션을 선택하세요.

색인된 카탈로그는 모든 볼륨과 백업 파일을 추적하여 검색을 빠르고 효율적으로 수행할 수 있도록 해줍니다.

자세한 내용은 을 https://docs.netapp.com/us-en/bluexp-backup-recovery/prev-ontap-restore.html["검색 및 복원에 대한 인덱싱 활성화"]참조하십시오.



==== Azure 개인 링크 엔드포인트 및 서비스 엔드포인트

일반적으로 BlueXP backup and recovery 클라우드 공급자와 개인 엔드포인트를 설정하여 보호 작업을 처리합니다. 이번 릴리스에서는 BlueXP 백업 및 복구가 프라이빗 엔드포인트를 자동으로 생성하는 것을 활성화 또는 비활성화할 수 있는 선택적 설정이 도입되었습니다. 프라이빗 엔드포인트 생성 프로세스를 더욱 세부적으로 제어하려는 경우 이 기능이 유용할 수 있습니다.

보호 기능을 활성화하거나 복원 프로세스를 시작할 때 이 옵션을 활성화하거나 비활성화할 수 있습니다.

이 설정을 비활성화하면 BlueXP 백업 및 복구가 제대로 작동하도록 개인 엔드포인트를 수동으로 생성해야 합니다. 연결이 제대로 되지 않으면 백업 및 복구 작업을 제대로 수행하지 못할 수 있습니다.



==== ONTAP S3에서 SnapMirror to Cloud Resync 지원

이전 릴리스에서는 SnapMirror to Cloud Resync(SM-C Resync) 지원이 도입되었습니다. 이 기능은 NetApp 환경에서 볼륨 마이그레이션 시 데이터 보호를 간소화합니다. 이번 릴리스에서는 ONTAP S3뿐 아니라 Wasabi, MinIO와 같은 다른 S3 호환 공급업체에서도 SM-C Resync를 지원합니다.



==== StorageGRID용 자체 버킷 가져오기

작업 환경의 개체 스토리지에 백업 파일을 생성할 때, 기본적으로 BlueXP 백업 및 복구는 사용자가 구성한 개체 스토리지 계정에 백업 파일의 컨테이너(버킷 또는 스토리지 계정)를 생성합니다. 이전에는 이를 재정의하여 Amazon S3, Azure Blob Storage 및 Google Cloud Storage에 대한 자체 컨테이너를 지정할 수 있었습니다. 이번 릴리스에서는 자체 StorageGRID 개체 스토리지 컨테이너를 사용할 수 있습니다.

을 https://docs.netapp.com/us-en/bluexp-backup-recovery/prev-ontap-protect-journey.html["나만의 객체 스토리지 컨테이너를 만드세요"]참조하십시오.



== 분류



=== 2025년 8월 11일



==== 버전 1.46

이 BlueXP classification 릴리스에는 버그 수정과 다음 업데이트가 포함되어 있습니다.

.BlueXP 타임라인에서 향상된 스캔 이벤트 통찰력
이제 BlueXP 타임라인은 BlueXP classification 위한 스캔 이벤트에 대한 향상된 통찰력을 지원합니다. 이제 타임라인에는 작업 환경 스캔이 시작되는 시점, 작업 환경의 상태, 문제가 표시됩니다. 공유 및 작업 환경의 상태는 매핑 스캔에만 사용할 수 있습니다.

BlueXP 타임라인에 대한 자세한 내용은 다음을 참조하세요.link:https://docs.netapp.com/us-en/bluexp-setup-admin/task-monitor-cm-operations.html["BlueXP 작업 모니터링"^] .

.RHEL 9.6 지원
이 릴리스에서는 다크 사이트 배포를 포함하여 BlueXP classification 의 수동 온프레미스 설치를 위한 Red Hat Enterprise Linux v9.6에 대한 지원이 추가되었습니다.

다음 운영 체제는 Podman 컨테이너 엔진을 사용해야 하며 BlueXP  분류 버전 1.30 이상이 필요합니다. Red Hat Enterprise Linux 버전 8.8, 8.10, 9.0, 9.1, 9.2, 9.3, 9.4 및 9.5.



=== 2025년 7월 14일



==== 버전 1.45

이 BlueXP classification 릴리스에는 리소스 활용도를 최적화하는 코드 변경 사항이 포함되어 있습니다.

.스캔을 위해 파일 공유를 추가하는 향상된 워크플로
파일 공유 그룹에 파일 공유를 추가하는 워크플로가 간소화되었습니다. 또한, 이제 인증 유형(Kerberos 또는 NTLM)에 따라 CIFS 프로토콜 지원이 차별화됩니다.

자세한 내용은 을 link:https://docs.netapp.com/us-en/bluexp-classification/task-scanning-file-shares.html["파일 공유를 스캔합니다"]참조하십시오.

.향상된 파일 소유자 정보
이제 조사 탭에서 캡처된 파일의 파일 소유자에 대한 자세한 정보를 볼 수 있습니다. 조사 탭에서 파일의 메타데이터를 볼 때 파일 소유자를 찾은 다음 **세부 정보 보기**를 선택하면 사용자 이름, 이메일, SAM 계정 이름을 확인할 수 있습니다. 이 사용자가 소유한 다른 항목도 볼 수 있습니다. 이 기능은 Active Directory가 설치된 작업 환경에서만 사용할 수 있습니다.

자세한 내용은 을 link:https://docs.netapp.com/us-en/bluexp-classification/task-investigate-data.html["조직에 저장된 데이터를 조사합니다"]참조하십시오.



=== 2025년 6월 10일



==== 버전 1.44

이 BlueXP  분류 릴리스에는 다음이 포함됩니다.

.거버넌스 대시보드의 업데이트 시간이 개선되었습니다.
거버넌스 대시보드의 개별 구성 요소에 대한 업데이트 시간이 개선되었습니다. 다음 표는 각 구성 요소의 업데이트 빈도를 보여줍니다.

[cols="1,1"]
|===
| 구성 요소 | 업데이트 시간 


| 데이터 사용 기간 | 24시간 


| 범주 | 24시간 


| 데이터 개요 | 5분 


| 중복 파일 | 2시간 


| 파일 형식 | 24시간 


| 비업무용 데이터 | 2시간 


| 사용 권한을 엽니다 | 24시간 


| 저장된 검색 | 2시간 


| 민감한 데이터 및 광범위한 권한 | 24시간 


| 데이터 크기 | 24시간 


| 오래된 데이터 | 2시간 


| 민감도 수준별 상위 데이터 저장소 | 2시간 
|===
마지막 업데이트 시간을 확인하고 중복 파일, 비업무용 데이터, 저장된 검색, 오래된 데이터, 민감도 수준별 상위 데이터 저장소 구성 요소를 수동으로 업데이트할 수 있습니다. 거버넌스 대시보드에 대한 자세한 내용은 다음을 참조하세요. link:https://docs.netapp.com/us-en/bluexp-classification/task-controlling-governance-data.html["조직에 저장된 데이터에 대한 거버넌스 세부 정보를 봅니다"] .

.성능 및 보안 개선
BlueXP 분류의 성능, 메모리 소비, 보안을 개선하기 위해 개선 사항이 적용되었습니다.

.버그 수정
Redis가 업그레이드되어 BlueXP 분류의 안정성이 향상되었습니다. BlueXP 분류는 이제 Elasticsearch를 사용하여 스캔 중 파일 개수 보고의 정확도를 높였습니다.



=== 2025년 5월 12일



==== 버전 1.43

이 BlueXP  분류 릴리스에는 다음이 포함됩니다.

.분류 스캔의 우선 순위를 지정합니다
BlueXP  분류는 매핑 전용 스캔뿐만 아니라 스캔 지도 및 분류 우선 순위를 지정할 수 있는 기능을 지원하므로 먼저 완료된 스캔을 선택할 수 있습니다. 맵 및 분류 스캔의 우선 순위는 스캔이 시작되는 동안과 그 전에 지원됩니다. 스캔이 진행 중일 때 스캔 우선 순위를 지정하도록 선택하면 매핑 및 분류 스캔이 모두 우선 순위가 지정됩니다.

자세한 내용은 을 link:https://docs.netapp.com/us-en/bluexp-classification/task-managing-repo-scanning.html#prioritize-scans["스캔 우선 순위 지정"]참조하십시오.

.캐나다 PII(개인 식별 정보) 데이터 범주 지원
BlueXP  분류 스캔은 캐나다 PII 데이터 범주를 식별합니다. 이러한 범주에는 은행 정보, 여권 번호, 사회 보험 번호, 운전면허증 번호 및 모든 캐나다 주 및 영토에 대한 건강 카드 번호가 포함됩니다.

자세한 내용은 을 link:https://docs.netapp.com/us-en/bluexp-classification/reference-private-data-categories.html#types-of-personal-data["개인 데이터 범주"]참조하십시오.

.사용자 지정 분류(미리 보기)
BlueXP  분류는 지도 및 분류 스캔에 대한 사용자 정의 분류를 지원합니다. 사용자 지정 분류를 사용하면 정규식을 사용하여 조직 고유의 데이터를 캡처하도록 BlueXP  스캔을 조정할 수 있습니다. 이 기능은 현재 미리보기 중입니다.

자세한 내용은 을 link:https://docs.netapp.com/us-en/bluexp-classification/task-custom-classification.html["사용자 지정 분류를 추가합니다"]참조하십시오.

.저장된 검색 탭
** Policies** 탭의 이름이 link:https://docs.netapp.com/us-en/bluexp-classification/task-using-policies.html["** 저장된 검색**"]변경되었습니다. 기능은 변경되지 않았습니다.

.스캔 이벤트를 BlueXP  타임라인으로 보냅니다
BlueXP  분류는 에 분류 이벤트(스캔이 시작되었을 때 및 종료되었을 때)를 보낼 수 있도록 link:https://docs.netapp.com/us-en/bluexp-setup-admin/task-monitor-cm-operations.html#audit-user-activity-from-the-bluexp-timeline["BlueXP  타임라인"^]지원합니다.

.보안 업데이트
* Keras 패키지가 업데이트되어 취약점을 완화합니다(BDSA-2025-0107 및 BDSA-2025-1984).
* Docker 컨테이너 구성이 업데이트되었습니다. 컨테이너는 더 이상 원시 네트워크 패킷을 만들기 위해 호스트의 네트워크 인터페이스에 액세스할 수 없습니다. 이 업데이트는 불필요한 액세스를 줄여 잠재적인 보안 위험을 완화합니다.


.성능 향상
RAM 사용을 줄이고 BlueXP  분류의 전반적인 성능을 개선하기 위해 코드 개선 사항이 구현되었습니다.

.버그 수정
StorageGRID 검사가 실패하고, 조사 페이지 필터 옵션이 로드되지 않으며, 대량 평가를 위해 다운로드되지 않는 데이터 검색 평가가 수정되었습니다.



=== 2025년 4월 14일



==== 버전 1.42

이 BlueXP  분류 릴리스에는 다음이 포함됩니다.

.작업 환경을 위한 대량 스캔
BlueXP  분류는 작업 환경에 대한 대량 작업을 지원합니다. 스캔 매핑 활성화, 스캔 매핑 및 분류 활성화, 스캔 비활성화 또는 작업 환경의 볼륨에 대한 사용자 정의 구성 생성을 선택할 수 있습니다. 개별 볼륨에 대해 선택하면 대량 선택이 무시됩니다. 대량 작업을 수행하려면 ** 구성** 페이지로 이동하여 선택합니다.

.조사 보고서를 로컬로 다운로드합니다
BlueXP  분류는 데이터 조사 보고서를 로컬로 다운로드하여 브라우저에서 볼 수 있는 기능을 지원합니다. 로컬 옵션을 선택하면 데이터 조사는 CSV 형식으로만 사용할 수 있으며 처음 10,000개의 데이터 행만 표시됩니다.

자세한 내용은 을 link:https://docs.netapp.com/us-en/bluexp-classification/task-investigate-data.html#create-the-data-investigation-report["BlueXP  분류를 통해 조직에 저장된 데이터를 조사합니다"]참조하십시오.



=== 2025년 3월 10일



==== 버전 1.41

이 BlueXP  분류 릴리스에는 일반적인 개선 사항 및 버그 수정이 포함되어 있습니다. 여기에는 다음이 포함됩니다.

.스캔 상태
BlueXP  분류는 볼륨에서 _initial_mapping 및 분류 스캔의 실시간 진행 상황을 추적합니다. 별도의 프로그레시브 바는 매핑 및 분류 스캔을 추적하여 스캔된 총 파일의 백분율을 표시합니다. 진행 표시줄 위로 마우스를 가져가면 스캔한 파일 수와 총 파일 수를 볼 수도 있습니다. 스캔 상태를 추적하면 스캔 진행 상황을 더 자세히 파악할 수 있으므로 스캔 계획을 개선하고 리소스 할당을 이해할 수 있습니다.

스캔 상태를 보려면 BlueXP  분류에서 ** 구성**으로 이동한 다음 ** 작업 환경 구성** 을 선택합니다. 진행 상황은 각 볼륨에 대해 일렬로 표시됩니다.



=== 2025년 2월 19일



==== 버전 1.40

이 BlueXP  분류 릴리스에는 다음 업데이트가 포함됩니다.

.RHEL 9.5 지원
이 릴리스는 Red Hat Enterprise Linux v9.5 및 이전에 지원되는 버전을 지원합니다. 이는 다크 사이트 배포를 포함하여 BlueXP  분류의 수동 온-프레미스 설치에 적용됩니다.

다음 운영 체제는 Podman 컨테이너 엔진을 사용해야 하며 BlueXP  분류 버전 1.30 이상이 필요합니다. Red Hat Enterprise Linux 버전 8.8, 8.10, 9.0, 9.1, 9.2, 9.3, 9.4 및 9.5.

.매핑 전용 스캔의 우선 순위를 지정합니다
매핑 전용 스캔을 수행할 때 가장 중요한 스캔의 우선 순위를 지정할 수 있습니다. 이 기능은 작업 환경이 많고 우선 순위가 높은 검사가 먼저 완료되도록 하려는 경우에 유용합니다.

기본적으로 스캔은 시작된 순서에 따라 대기합니다. 스캔 우선 순위 지정 기능을 통해 스캔을 대기열 앞으로 이동할 수 있습니다. 여러 스캔의 우선 순위를 지정할 수 있습니다. 우선 순위는 선입선출 순서로 지정됩니다. 즉, 우선 순위를 지정한 첫 번째 스캔이 대기열의 맨 앞으로 이동하고 우선 순위를 지정한 두 번째 스캔은 대기열의 두 번째 스캔이 됩니다.

우선 순위는 한 번만 부여됩니다. 매핑 데이터의 자동 재검색이 기본 순서로 수행됩니다.

우선 순위 지정은 로 link:https://docs.netapp.com/us-en/bluexp-classification/concept-cloud-compliance.html["매핑 전용 스캔"^]제한됩니다. 스캔 맵과 분류에는 사용할 수 없습니다.

자세한 내용은 을 link:https://docs.netapp.com/us-en/bluexp-classification/task-managing-repo-scanning.html#prioritize-scans["스캔 우선 순위 지정"^]참조하십시오.

.모든 스캔을 재시도합니다
BlueXP  분류는 실패한 모든 스캔을 일괄 재시도하는 기능을 지원합니다.

** Retry All** 기능을 사용하여 일괄 작업으로 스캔을 다시 시도할 수 있습니다. 네트워크 중단과 같은 일시적인 문제로 인해 분류 스캔이 실패하는 경우 개별적으로 다시 시도하지 않고 하나의 버튼으로 모든 스캔을 동시에 다시 시도할 수 있습니다. 스캔은 필요한 만큼 재시도할 수 있습니다.

모든 스캔을 재시도하려면:

. BlueXP  classification 메뉴에서 * Configuration * 을 선택합니다.
. 실패한 모든 스캔을 다시 시도하려면 * 모든 스캔 재시도 * 를 선택합니다.


.범주화 모델 정확도 향상
의 머신 러닝 모델의 정확도는 link:https://docs.netapp.com/us-en/bluexp-classification/reference-private-data-categories.html#types-of-sensitive-personal-datapredefined-categories["미리 정의된 범주"]11% 향상되었습니다.



=== 2025년 1월 22일



==== 버전 1.39

이 BlueXP  분류 릴리스는 데이터 조사 보고서의 내보내기 프로세스를 업데이트합니다. 이 내보내기 업데이트는 데이터에 대한 추가 분석을 수행하거나, 데이터에 대한 추가 시각화를 만들거나, 데이터 조사 결과를 다른 사람과 공유하는 데 유용합니다.

이전에는 데이터 조사 보고서 내보내기가 10,000행으로 제한되었습니다. 이 릴리스에서는 모든 데이터를 내보낼 수 있도록 제한이 제거되었습니다. 이 변경 사항을 통해 데이터 조사 보고서에서 더 많은 데이터를 내보낼 수 있으므로 보다 유연하게 데이터를 분석할 수 있습니다.

작업 환경, 볼륨, 대상 폴더 및 JSON 또는 CSV 형식을 선택할 수 있습니다. 내보낸 파일 이름에는 타임스탬프가 포함되어 있어 데이터를 내보낸 시기를 식별할 수 있습니다.

지원되는 작업 환경은 다음과 같습니다.

* Cloud Volumes ONTAP
* ONTAP용 FSX
* ONTAP
* 공유 그룹


데이터 조사 보고서에서 데이터를 내보내는 데는 다음과 같은 제한 사항이 있습니다.

* 다운로드할 최대 레코드 수는 유형(파일, 디렉터리 및 테이블)당 5억 개입니다.
* 100만 개의 레코드를 내보내는 데 약 35분이 걸릴 것으로 예상됩니다.


데이터 조사 및 보고서에 대한 자세한 내용은 을 참조하십시오 https://docs.netapp.com/us-en/bluexp-classification/task-investigate-data.html["조직에 저장된 데이터를 조사합니다"].



=== 2024년 12월 16일



==== 버전 1.38

이 BlueXP  분류 릴리스에는 일반적인 개선 사항 및 버그 수정이 포함되어 있습니다.



== Cloud Volumes ONTAP



=== 2025년 8월 11일



==== 최적화된 라이선스의 사용 가능 기간이 종료되었습니다.

2025년 8월 11일부터 Cloud Volumes ONTAP Optimized 라이선스는 더 이상 사용되지 않으며 Azure 및 Google Cloud 마켓플레이스에서 PAYGO(종량제) 구독을 구매하거나 갱신할 수 없습니다. 최적화된 라이선스에 대한 기존 연간 계약이 있는 경우, 계약 기간이 끝날 때까지 라이선스를 계속 사용할 수 있습니다. 최적화된 라이선스가 만료되면 Cloud Volumes ONTAP Essentials 또는 Professional 라이선스를 선택할 수 있습니다.

하지만 최적화된 라이선스를 추가하거나 갱신하는 기능은 API를 통해 제공될 예정입니다.

라이센스 패키지에 대한 정보는 다음을 참조하세요. https://docs.netapp.com/us-en/bluexp-cloud-volumes-ontap/concept-licensing.html["Cloud Volumes ONTAP 라이선싱"^] .

다른 충전 방법으로 전환하는 방법에 대한 정보는 다음을 참조하세요. https://docs.netapp.com/us-en/bluexp-cloud-volumes-ontap/task-manage-capacity-licenses.html["용량 기반 라이선싱 관리"^] .



=== 2025년 7월 14일



==== 투명 프록시 지원

BlueXP 이제 기존 명시적 프록시 연결 외에도 투명 프록시 서버를 지원합니다. BlueXP 커넥터를 생성하거나 수정할 때 Cloud Volumes ONTAP 과의 네트워크 트래픽을 안전하게 관리하도록 투명 프록시 서버를 구성할 수 있습니다.

Cloud Volumes ONTAP 에서 프록시 서버를 사용하는 방법에 대한 자세한 내용은 다음을 참조하세요.

* https://docs.netapp.com/us-en/bluexp-cloud-volumes-ontap/reference-networking-aws.html#network-configurations-to-support-connector-proxy-servers["AWS에서 커넥터 프록시를 지원하는 네트워크 구성"^]
* https://docs.netapp.com/us-en/bluexp-cloud-volumes-ontap/azure/reference-networking-azure.html#network-configurations-to-support-connector["Azure에서 커넥터 프록시를 지원하는 네트워크 구성"^]
* https://docs.netapp.com/us-en/bluexp-cloud-volumes-ontap/reference-networking-gcp.html#network-configurations-to-support-connector-proxy["Google Cloud에서 커넥터 프록시를 지원하는 네트워크 구성"^]




==== Azure의 Cloud Volumes ONTAP 에 대해 지원되는 새로운 VM 유형

Cloud Volumes ONTAP 9.13.1부터 L8s_v3는 새 고가용성(HA) 쌍 배포와 기존 고가용성(HA) 쌍 배포 모두에 대해 Azure 단일 및 다중 가용성 영역에서 VM 유형으로 지원됩니다.

자세한 내용은 을 https://docs.netapp.com/us-en/cloud-volumes-ontap-relnotes/reference-configs-azure.html["Azure에서 지원되는 구성"^]참조하십시오.



=== 2025년 6월 25일



==== Cloud Volumes ONTAP 에 대한 BYOL 라이선싱의 제한된 가용성

2025년 6월 25일부터 NetApp Cloud Volumes ONTAP 의 BYOL(Bring Your Own License) 라이선스 모델을 제한했습니다. 이 제한은 AWS, Azure, Google Cloud의 모든 고객 및 Cloud Volumes ONTAP 배포에 적용됩니다. 미국 공공 부문 고객과 중국 리전 배포는 예외입니다.

NetApp 지원 및 서비스는 BYOL 계약이 만료될 때까지 계속되지만, 만료된 라이선스는 갱신 또는 연장되지 않습니다. BYOL 라이선스가 만료되면 클라우드 마켓플레이스 구독을 통해 구매한 용량 기반 라이선스로 교체해야 합니다. 하이퍼스케일러 마켓플레이스를 통한 용량 기반 라이선스 모델은 라이선스 경험을 간소화하고 더 큰 비즈니스 이점을 제공합니다. 전환 옵션에 대해 논의하려면 NetApp 계정 팀 또는 고객 성공 담당자에게 문의하십시오.

자세한 내용은 다음 고객 공지문을 참조하세요.  https://mysupport.netapp.com/info/communications/CPC-00661.html["CPC-00661: Cloud Volumes ONTAP BYOL 정책 변경"^] .



== 복사 및 동기화



=== 2025년 2월 2일



==== 데이터 브로커를 위한 새로운 OS 지원

이제 Red Hat Enterprise 9.4, Ubuntu 23.04 및 Ubuntu 24.04를 실행하는 호스트에서 데이터 브로커가 지원됩니다.

https://docs.netapp.com/us-en/bluexp-copy-sync/task-installing-linux.html#linux-host-requirements["Linux 호스트 요구 사항 보기"]..



=== 2024년 10월 27일



==== 버그 수정

BlueXP 복사본 및 동기화 서비스와 데이터 브로커를 업데이트하여 몇 가지 버그를 수정했습니다. 새 데이터 브로커 버전은 1.0.56입니다.



=== 2024년 9월 16일



==== 버그 수정

BlueXP 복사본 및 동기화 서비스와 데이터 브로커를 업데이트하여 몇 가지 버그를 수정했습니다. 새 데이터 브로커 버전은 1.0.55입니다.



== 디지털 자문업체



=== 2025년 8월 6일



==== 지원 권한 스위치

이제 지원 자격이 있는 Brocade Fibre Channel SAN 스위치에 대한 정보를 볼 수 있습니다. 여기에는 스위치 모델, 일련 번호, 지원 상태에 대한 세부 정보가 포함됩니다. link:https://docs.netapp.com/us-en/active-iq/task_view_inventory_details.html["지원 권한이 있는 스위치를 보는 방법을 알아보세요."] .



==== RSS AutoSupport 데이터에 대한 임계값

AutoSupport 위젯의 최근 전송 중지된 RSS(RSS) 제한이 시스템이 RSS로 표시되기 전까지 48시간(2일)에서 216시간(9일)으로 연장되었습니다. 이는 주간 AutoSupport 데이터만 전송하는 StorageGRID 와 같은 플랫폼을 수용하기 위해 수행됩니다.



==== Digital Advisor API 카탈로그의 더 이상 사용되지 않는 API 섹션

Digital Advisor API 카탈로그에서 더 이상 사용되지 않는 새로운 API 섹션을 사용할 수 있습니다. 여기에는 지원 중단이 예정된 API, 지원 중단 일정 및 대체 API가 나열되어 있습니다.



==== 용량 예측 V2 및 지원 종료 API 모듈 사용 중단

용량 예측 V2 및 지원 종료 API 모듈은 사용 중단될 예정입니다. 더 이상 지원되지 않는 API에 액세스하거나 지원 중단 일정과 대체 API에 대해 알아보려면 *API 서비스 -> 찾아보기 -> 더 이상 지원되지 않는 API*로 이동하세요.



=== 2025년 7월 9일



==== Upgrade Advisor

* ONTAP 업그레이드 계획을 간소화하고 잠재적인 방해 요소 또는 경고를 해결하기 위해 업그레이드 어드바이저 플랜에 다양한 형식의 다운로드 옵션이 추가되었습니다. 이제 업그레이드 어드바이저 플랜을 Excel, PDF, JSON 형식으로 다운로드할 수 있습니다.
* 업그레이드 어드바이저 계획의 Excel 형식에는 다음과 같은 개선 사항이 적용되었습니다.
+
** 클러스터에서 수행된 사전 점검 내용을 확인하고 결과에 "통과", "실패", "건너뜀"과 같은 표시기를 표시할 수 있습니다. 이를 통해 클러스터가 ONTAP 업그레이드를 완료하기에 최적의 상태인지 확인할 수 있습니다.
** ONTAP 대상 버전과 함께 제공된 버전과 함께 클러스터에 적용 가능한 권장 최신 펌웨어 업데이트를 볼 수 있습니다.
** SAN 클러스터의 상호 운용성 검사를 제공하는 새 탭이 추가되었습니다. 이 탭 은 선택한 대상 ONTAP 버전에 지원되는 호스트 OS 버전을 보여줍니다.






=== 2025년 5월 8일



==== AutoSupport 위젯

AutoSupport 데이터 전송을 중지한 시스템에 대한 세부 정보를 제공하는 팝업을 포함하도록 AutoSupport 위젯이 향상되었습니다. AutoSupport를 사용하면 다운타임 위험을 줄이고 사전 예방적인 시스템 상태 관리를 지원할 수 있습니다.



==== 지원 계약 보고서

새로운 ASP/LSG 플래그 필드를 포함하도록 지원 계약 보고서가 향상되었습니다. 이 필드에서 공인 지원 파트너가 지원하는 시스템, 즉 라이프사이클 서비스 인증을 필터링하고 식별할 수 있습니다.



==== Sustainability 대시보드

이제 Sustainability 프레젠테이션에 포함된 링크를 사용하여 Sustainability 대시보드를 시작할 수 있습니다.



== 디지털 지갑



=== 2025년 3월 10일



==== 구독을 제거할 수 있습니다

이제 구독을 취소한 경우 디지털 지갑에서 구독을 제거할 수 있습니다.



==== 마켓플레이스 구독에 사용된 용량 보기

PAYGO 서브스크립션을 볼 때 서브스크립션의 소비 용량을 볼 수 있습니다.



=== 2025년 2월 10일

BlueXP  디지털 지갑은 사용하기 쉽도록 다시 디자인되었으며 이제 추가 구독 및 라이선스 관리 기능을 제공합니다.



==== 새로운 개요 대시보드

디지털 지갑 홈페이지에는 NetApp 라이선스 및 마켓플레이스 구독에 대한 업데이트된 대시보드가 있으며, 특정 서비스, 라이선스 유형 및 필요한 작업을 드릴다운할 수 있습니다.



==== 자격 증명에 대한 구독을 구성하는 중입니다

이제 BlueXP  디지털 지갑을 사용하여 공급자 자격 증명에 대한 구독을 구성할 수 있습니다. 일반적으로 마켓플레이스 구독 또는 연간 계약을 처음 구독할 때 이 작업을 수행합니다. 이전에는 구독 자격 증명을 변경할 수 있었습니다. 자격 증명 페이지에서만 변경할 수 있었습니다.



==== 구독을 조직과 연결합니다

이제 구독이 디지털 지갑에서 직접 연결되는 조직을 업데이트할 수 있습니다.



==== Cloud Volume ONTAP 라이센스 관리

이제 홈 페이지 또는 * Direct licenses * 탭을 통해 Cloud Volumes ONTAP 라이센스를 관리할 수 있습니다. 마켓플레이스 구독 * 탭을 사용하여 구독 정보를 봅니다.



=== 2024년 3월 5일



==== BlueXP 재해 복구

BlueXP 디지털 지갑을 통해 이제 BlueXP 재해 복구용 라이센스를 관리할 수 있습니다. 라이센스를 추가하고 라이센스를 업데이트하며 라이센스 용량에 대한 세부 정보를 볼 수 있습니다.

https://docs.netapp.com/us-en/bluexp-digital-wallet/task-manage-data-services-licenses.html["BlueXP 데이터 서비스용 라이센스를 관리하는 방법에 관해 알아보십시오"]



=== 2023년 7월 30일



==== 사용 보고서 기능 향상

이제 Cloud Volumes ONTAP 사용 보고서의 몇 가지 개선 사항이 있습니다.

* 이제 TiB 단위는 컬럼 이름에 포함됩니다.
* 이제 일련 번호에 대한 new_node_field가 포함됩니다.
* 이제 Storage VMs Usage 보고서에 new_Workload Type_column이 포함됩니다.
* 이제 작업 환경 이름이 스토리지 VM 및 볼륨 사용 보고서에 포함됩니다.
* 이제 볼륨 type_file_은 _Primary(읽기/쓰기)_로 레이블이 지정됩니다.
* 이제 볼륨 type_secondary_이(가) _Secondary(DP)_로 표시됩니다.


사용 현황 보고서에 대한 자세한 내용은 을 참조하십시오 https://docs.netapp.com/us-en/bluexp-digital-wallet/task-manage-capacity-licenses.html#download-usage-reports["사용 보고서를 다운로드합니다"].



== 재해 복구



=== 2025년 8월 4일

버전 4.2.5P2



==== BlueXP disaster recovery 업데이트

이 릴리스에는 다음 업데이트가 포함됩니다.

* 여러 스토리지 가상 머신에서 제공되는 동일한 LUN을 처리하기 위해 VMFS 지원이 개선되었습니다.
* 이미 마운트 해제되거나 삭제된 데이터 저장소를 처리하기 위해 테스트 해체 정리를 개선했습니다.
* 제공된 네트워크 내에 입력된 게이트웨이가 포함되어 있는지 확인할 수 있도록 서브넷 매핑이 개선되었습니다.
* VM 이름에 ".com"이 포함되어 있는 경우 복제 계획이 실패할 수 있는 문제를 수정했습니다.
* 복제 계획 생성의 일부로 볼륨을 생성할 때 대상 볼륨이 소스 볼륨과 동일하지 않도록 하는 제한이 제거되었습니다.
* Azure Marketplace에서 NetApp Intelligent Services에 대한 PAYGO(종량제) 구독 지원을 추가하고 무료 평가판 대화 상자에 Azure Marketplace에 대한 링크를 추가했습니다.
+
자세한 내용은 다음을 참조하세요. https://docs.netapp.com/us-en/bluexp-disaster-recovery/get-started/dr-intro.html#licensing["BlueXP disaster recovery 라이선스"] 그리고 https://docs.netapp.com/us-en/bluexp-disaster-recovery/get-started/dr-licensing.html["BlueXP disaster recovery 위한 라이선싱 설정"] .





=== 2025년 7월 14일

버전 4.2.5



==== BlueXP disaster recovery 의 사용자 역할

BlueXP disaster recovery 이제 각 사용자가 특정 기능과 작업에 대해 갖는 액세스를 관리하는 역할을 사용합니다.

이 서비스는 BlueXP disaster recovery 에 특정한 다음 역할을 사용합니다.

* *재해 복구 관리자*: BlueXP disaster recovery 에서 모든 작업을 수행합니다.
* *재해 복구 장애 조치 관리자*: BlueXP disaster recovery 에서 장애 조치 및 마이그레이션 작업을 수행합니다.
* *재해 복구 애플리케이션 관리자*: 복제 계획을 만들고 수정하고 테스트 장애 조치를 시작합니다.
* *재해 복구 뷰어*: BlueXP disaster recovery 에서 정보를 볼 수 있지만, 어떤 작업도 수행할 수 없습니다.


BlueXP disaster recovery 서비스를 클릭하고 처음으로 구성하는 경우 *SnapCenterAdmin* 권한이나 *조직 관리자* 역할이 있어야 합니다.

자세한 내용은 을 참조하십시오  https://docs.netapp.com/us-en/bluexp-disaster-recovery/reference/dr-reference-roles.html["BlueXP disaster recovery 의 사용자 역할 및 권한"].

https://docs.netapp.com/us-en/bluexp-setup-admin/reference-iam-predefined-roles.html["모든 서비스에 대한 BlueXP 액세스 역할에 대해 알아보세요"^]..



==== BlueXP disaster recovery 의 기타 업데이트

* 향상된 네트워크 검색
* 확장성 개선:
+
** 모든 세부 정보 대신 필요한 메타데이터만 필터링
** VM 리소스를 더 빠르게 검색하고 업데이트하기 위한 검색 개선
** 데이터 검색 및 데이터 업데이트를 위한 메모리 최적화 및 성능 최적화
** vCenter SDK 클라이언트 생성 및 풀 관리 개선


* 다음 예약 또는 수동 검색 시 오래된 데이터 관리:
+
** vCenter에서 VM이 삭제되면 이제 BlueXP disaster recovery 복제 계획에서 자동으로 해당 VM을 제거합니다.
** vCenter에서 데이터 저장소 또는 네트워크가 삭제되면 이제 BlueXP disaster recovery 복제 계획 및 리소스 그룹에서도 해당 데이터 저장소 또는 네트워크를 삭제합니다.
** vCenter에서 클러스터, 호스트 또는 데이터 센터가 삭제되면 이제 BlueXP disaster recovery 복제 계획 및 리소스 그룹에서도 이를 삭제합니다.


* 이제 브라우저의 시크릿 모드에서 Swagger 문서에 액세스할 수 있습니다. BlueXP disaster recovery 환경에서는 설정 > API 문서에서 액세스할 수 있으며, 브라우저의 시크릿 모드에서 다음 URL을 통해 직접 액세스할 수도 있습니다.  https://snapcenter.cloudmanager.cloud.netapp.com/api/api-doc/draas["Swagger 문서"^] .
* 장애 복구 작업 후 일부 상황에서 iGroup이 작업 완료 후에도 남아 있는 경우가 있었습니다. 이 업데이트는 iGroup이 오래된 경우 제거합니다.
* 복제 계획에 NFS FQDN이 사용된 경우, BlueXP disaster recovery 이제 해당 FQDN을 IP 주소로 확인합니다. 이 업데이트는 재해 복구 사이트에서 FQDN을 확인할 수 없는 경우에 유용합니다.
* UI 정렬 개선
* 성공적인 검색 후 vCenter 크기 조정 세부 정보를 캡처하기 위한 로그 개선




=== 2025년 6월 30일

버전 4.2.4P2



==== 발견 개선

이 업데이트는 검색 프로세스를 개선하여 검색에 필요한 시간을 줄여줍니다.



=== 2025년 6월 23일

버전 4.2.4P1



==== 서브넷 매핑 개선

이번 업데이트에서는 새로운 검색 기능을 통해 서브넷 매핑 추가 및 편집 대화 상자가 개선되었습니다. 이제 검색어를 입력하여 특정 서브넷을 빠르게 찾을 수 있으므로 서브넷 매핑 관리가 더욱 간편해졌습니다.



=== 2025년 6월 9일

버전 4.2.4



==== Windows 로컬 관리자 암호 솔루션(LAPS) 지원

Windows 로컬 관리자 암호 솔루션(Windows LAPS)은 Active Directory의 로컬 관리자 계정의 암호를 자동으로 관리하고 백업하는 Windows 기능입니다.

이제 도메인 컨트롤러 정보를 제공하여 서브넷 매핑 옵션을 선택하고 LAPS 옵션을 선택할 수 있습니다. 이 옵션을 사용하면 각 가상 머신에 비밀번호를 입력할 필요가 없습니다.

자세한 내용은 을 https://docs.netapp.com/us-en/bluexp-disaster-recovery/use/drplan-create.html["복제 계획을 생성합니다"]참조하십시오.



== E-Series 시스템



=== 2025년 5월 12일



==== BlueXP 액세스 역할이 필요합니다

이제 BlueXP에서 E-Series를 보고, 검색하고, 관리하려면 다음 액세스 역할 중 하나가 필요합니다. 조직 관리자, 폴더 또는 프로젝트 관리자, 저장소 관리자 또는 시스템 상태 전문가입니다.  https://docs.netapp.com/us-en/bluexp/reference-iam-predefined-roles.html["BlueXP 액세스 역할에 대해 알아보세요."^]



=== 2022년 9월 18일



==== E-Series 지원

이제 BlueXP에서 E-Series 시스템을 직접 검색할 수 있습니다. E-Series 시스템에 대해 살펴보고 하이브리드 멀티 클라우드 전체의 데이터를 완벽하게 파악할 수 있습니다.



== 경제적인 효율성



=== 2024년 5월 15일



==== 비활성화된 기능

일부 BlueXP 의 경제적 효율성 기능이 일시적으로 비활성화되었습니다.

* 기술 교체
* 용량 추가




=== 2024년 3월 14일



==== 기술 업데이트 옵션

기존 자산이 있고 기술을 업데이트해야 하는지 여부를 확인하려면 BlueXP의 경제적 효율성 기술 업데이트 옵션을 사용할 수 있습니다. 현재 워크로드에 대한 간단한 평가를 검토하여 추천을 하거나 지난 90일 이내에 AutoSupport 로그를 NetApp에 보낸 경우, 이제 워크로드 시뮬레이션을 제공하여 새로운 하드웨어에서 워크로드가 어떻게 수행되는지 확인할 수 있습니다.

또한 워크로드를 추가하고 기존 워크로드를 시뮬레이션에서 제외할 수 있습니다.

이전에는 자산을 평가하고 기술 업데이트가 필요한지 여부만 파악할 수 있었습니다.

이 기능은 이제 왼쪽 탐색 창의 Tech Refresh 옵션에 포함됩니다.

에 대해 자세히 https://docs.netapp.com/us-en/bluexp-economic-efficiency/use/tech-refresh.html["기술 업데이트를 평가합니다"] 알아보십시오.



=== 2023년 11월 8일



==== 기술 교체

이번 BlueXP의 경제적 효율성 릴리즈에는 자산을 평가하고 기술 업데이트가 권장되는지 여부를 확인할 수 있는 새로운 옵션이 포함되어 있습니다. 이 서비스에는 왼쪽 탐색 창에 있는 새로운 기술 업데이트 옵션, 현재 워크로드와 자산을 평가할 수 있는 새 페이지, 권장사항이 있는 보고서가 포함되어 있습니다.



== 에지 캐싱

BlueXP  에지 캐싱 서비스는 2024년 8월 7일에 제거되었습니다.



== Google Cloud NetApp 볼륨

<stdin>에 해결되지 않은 지시어가 있습니다 - include:: https://raw.githubusercontent.com/NetAppDocs/bluexp-google-cloud-netapp-volumes/main/whats-new.adoc [tag=whats-new,leveloffset=+1]



== Google 클라우드 스토리지



=== 2023년 7월 10일



==== 새로운 버킷을 추가하고 BlueXP의 기존 버킷을 관리할 수 있습니다

BlueXP Canvas에서 Google Cloud Storage 버킷을 한동안 볼 수 있었습니다. 이제 BlueXP 에서 직접 새 버킷을 추가하고 기존 버켓의 속성을 변경할 수 있습니다. https://docs.netapp.com/us-en/bluexp-google-cloud-storage/task-add-gcp-bucket.html["새로운 Google Cloud Storage 버킷을 추가하는 방법을 알아보십시오"]..



== 키스톤



=== 2025년 8월 5일



==== 인스턴스 수준 소비 데이터 보기

BlueXP 의 Keystone 대시보드를 통해 각 성능 서비스 수준 인스턴스의 현재 소비량과 과거 데이터를 볼 수 있습니다. 이 기능은 Keystone 버전 3(v3) 구독이 있는 경우 여러 인스턴스가 있는 성능 서비스 수준에서 사용할 수 있습니다. 자세한 내용은 다음을 참조하세요.link:https://docs.netapp.com/us-en/keystone-staas/integrations/current-usage-tab.html["Keystone 구독 사용량 보기"] .



== 쿠버네티스

Kubernetes 클러스터를 검색하고 관리하는 데 대한 지원이 2024년 8월 7일에 제거되었습니다.



== 마이그레이션 보고서

BlueXP  마이그레이션 보고서 서비스가 2024년 8월 7일에 제거되었습니다.



== 온프레미스 ONTAP 클러스터



=== 2025년 5월 12일



==== BlueXP 액세스 역할이 필요합니다

이제 온프레미스 ONTAP 클러스터를 보고, 검색하고, 관리하려면 다음 액세스 역할 중 하나가 필요합니다. 조직 관리자, 폴더 또는 프로젝트 관리자, 스토리지 관리자 또는 시스템 상태 전문가. link:https://docs.netapp.com/us-en/bluexp/concept-iam-predefined-roles.html["BlueXP 액세스 역할에 대해 알아보세요."^]



=== 2024년 11월 26일



==== 전용 모드로 ASA R2 시스템을 지원합니다

이제 프라이빗 모드에서 BlueXP 를 사용할 때 NetApp ASA R2 시스템을 검색할 수 있습니다. 이 지원은 BlueXP  3.9.46 비공개 모드 릴리즈부터 사용할 수 있습니다.

* https://docs.netapp.com/us-en/asa-r2/index.html["ASA R2 시스템에 대해 자세히 알아보십시오"^]
* https://docs.netapp.com/us-en/bluexp-setup-admin/concept-modes.html["BlueXP 배포 모드에 대해 알아보십시오"^]




=== 2024년 10월 7일



==== ASA R2 시스템 지원

이제 표준 모드 또는 제한된 모드에서 BlueXP 를 사용할 때 BlueXP 에서 NetApp ASA R2 시스템을 검색할 수 있습니다. NetApp ASA R2 시스템을 검색하고 작업 환경을 열면 바로 System Manager로 이동합니다.

ASA R2 시스템에서는 다른 관리 옵션을 사용할 수 없습니다. 표준 보기를 사용할 수 없으며 BlueXP 서비스를 활성화할 수 없습니다.

ASA R2 시스템 검색은 전용 모드에서 BlueXP 를 사용할 때 지원되지 않습니다.

* https://docs.netapp.com/us-en/asa-r2/index.html["ASA R2 시스템에 대해 자세히 알아보십시오"^]
* https://docs.netapp.com/us-en/bluexp-setup-admin/concept-modes.html["BlueXP 배포 모드에 대해 알아보십시오"^]




== 운영 복원력



=== 2023년 4월 2일



==== BlueXP  운영 복원력 서비스

새로운 BlueXP 운영 복구 서비스와 IT 운영 위험 개선 자동화 제안을 사용하면 운영 중단이나 장애가 발생하기 전에 권장 조치를 구현할 수 있습니다.

운영 복원력 은 서비스 및 솔루션의 상태, 가동 시간, 성능을 유지하기 위해 경고 및 이벤트를 분석하는 데 도움이 되는 서비스입니다.

link:https://docs.netapp.com/us-en/bluexp-operational-resiliency/get-started/intro.html["BlueXP 운영 복원성에 대해 자세히 알아보십시오"].



== 랜섬웨어 보호



=== 2025년 7월 15일



==== SAN 워크로드 지원

이 릴리스에는 BlueXP ransomware protection 의 SAN 워크로드 지원이 포함되어 있습니다. 이제 NFS 및 CIFS 워크로드 외에도 SAN 워크로드를 보호할 수 있습니다.

자세한 내용은 을 link:https://docs.netapp.com/us-en/bluexp-ransomware-protection/rp-start-prerequisites.html["BlueXP 랜섬웨어 방어의 사전 요구사항"]참조하십시오.



==== 향상된 작업 부하 보호

이번 릴리스에서는 SnapCenter 또는 BlueXP backup and recovery 와 같은 다른 NetApp 도구의 스냅샷 및 백업 정책을 사용하는 워크로드 구성 프로세스가 개선되었습니다. 이전 릴리스에서는 BlueXP ransomware protection 다른 도구의 정책을 감지하여 사용자가 감지 정책을 변경할 수만 있었습니다. 이번 릴리스에서는 스냅샷 및 백업 정책을 BlueXP ransomware protection 정책으로 바꾸거나 다른 도구의 정책을 계속 사용할 수 있습니다.

자세한 내용은 을 link:https://docs.netapp.com/us-en/bluexp-ransomware-protection/rp-use-protect.html["워크로드 보호"]참조하십시오.



==== 이메일 알림

BlueXP ransomware protection 잠재적인 공격을 감지하면 BlueXP 알림에 알림이 나타나고, 구성한 이메일 주소로 이메일이 전송됩니다.

이메일에는 심각도, 영향을 받는 워크로드, 그리고 BlueXP ransomware protection *알림* 탭에 있는 알림 링크가 포함됩니다.

BlueXP ransomware protection 에서 SIEM(보안 및 이벤트 관리) 시스템을 구성한 경우 해당 서비스는 SIEM 시스템으로 경고 세부 정보를 전송합니다.

자세한 내용은 을 link:https://docs.netapp.com/us-en/bluexp-ransomware-protection/rp-use-alert.html["감지된 랜섬웨어 알림 처리"]참조하십시오.



=== 2025년 6월 9일



==== 랜딩 페이지 업데이트

이번 릴리스에는 BlueXP 랜섬웨어 보호 기능의 랜딩 페이지가 업데이트되어 무료 평가판 시작과 검색이 더욱 쉬워졌습니다.



==== 준비 훈련 업데이트

이전에는 새로운 샘플 워크로드에 대한 공격을 시뮬레이션하여 랜섬웨어 대비 훈련을 실행할 수 있었습니다. 이 기능을 사용하면 시뮬레이션된 공격을 조사하고 워크로드를 복구할 수 있습니다. 이 기능을 사용하여 알림, 대응 및 복구를 테스트하세요. 필요에 따라 이러한 훈련을 실행하고 예약할 수 있습니다.

이번 릴리스에서는 BlueXP 랜섬웨어 보호 대시보드의 새 버튼을 사용하여 테스트 워크로드에 대한 랜섬웨어 준비 훈련을 실행할 수 있습니다. 이를 통해 제어된 환경 내에서 랜섬웨어 공격을 시뮬레이션하고, 그 영향을 조사하고, 워크로드를 효율적으로 복구하기가 더 쉬워졌습니다.

이제 NFS 워크로드뿐만 아니라 CIFS(SMB) 워크로드에 대한 준비 훈련을 실행할 수 있습니다.

자세한 내용은 을 https://docs.netapp.com/us-en/bluexp-ransomware-protection/rp-start-simulate.html["랜섬웨어 공격 준비도 훈련을 실시합니다"]참조하십시오.



==== BlueXP 분류 업데이트 활성화

BlueXP  랜섬웨어 보호 서비스 내에서 BlueXP  분류를 사용하려면 먼저 BlueXP  분류를 활성화하여 데이터를 스캔해야 합니다. 데이터를 분류하면 개인 식별 정보(PII)를 찾는 데 도움이 되며, 이는 보안 위험을 증가시킬 수 있습니다.

BlueXP 랜섬웨어 보호 기능 내에서 파일 공유 워크로드에 BlueXP 분류를 배포할 수 있습니다. *개인 정보 노출* 열에서 *노출 식별* 옵션을 선택하세요. 분류 서비스를 활성화한 경우, 이 작업을 통해 노출을 식별할 수 있습니다. 그렇지 않은 경우, 이번 릴리스에서는 BlueXP 분류 배포 옵션을 제공하는 대화 상자가 나타납니다. *배포*를 선택하면 BlueXP 분류 서비스 랜딩 페이지로 이동하여 해당 서비스를 배포할 수 있습니다. w

자세한 내용은 다음을 참조하세요.  https://docs.netapp.com/us-en/bluexp-classification/task-deploy-cloud-compliance.html["클라우드에 BlueXP 분류를 배포합니다"^] BlueXP 랜섬웨어 보호 서비스를 사용하려면 다음을 참조하세요.  https://docs.netapp.com/us-en/bluexp-ransomware-protection/rp-use-protect-classify.html["BlueXP  분류를 사용하여 개인 식별 정보를 검색합니다"] .



=== 2025년 5월 13일



==== BlueXP  랜섬웨어 보호에서 지원되지 않는 작업 환경에 대한 보고

검색 워크플로우에서 지원되는 워크로드 또는 지원되지 않는 워크로드 위에 마우스를 올리면 BlueXP  랜섬웨어 보호가 자세한 내용을 보고합니다. 이 교육은 일부 워크로드가 BlueXP  랜섬웨어 차단 서비스에서 검색되지 않는 이유를 파악하는 데 도움이 됩니다.

서비스가 작업 환경을 지원하지 않는 이유는 여러 가지가 있습니다. 예를 들어 작업 환경의 ONTAP 버전이 필요한 버전보다 낮을 수 있습니다. 지원되지 않는 작업 환경 위로 마우스를 가져가면 도구 설명에 그 이유가 표시됩니다.

초기 검색 중에 지원되지 않는 작업 환경을 볼 수 있으며, 여기서 결과를 다운로드할 수도 있습니다. 설정 페이지의 * 워크로드 검색 * 옵션에서 검색 결과를 볼 수도 있습니다.

자세한 내용은 을 https://docs.netapp.com/us-en/bluexp-ransomware-protection/rp-start-discover.html["BlueXP 랜섬웨어 방어에서 워크로드를 찾아보십시오"]참조하십시오.



=== 2025년 4월 29일



==== NetApp ONTAP용 Amazon FSx 지원

이 릴리즈는 Amazon FSx for NetApp ONTAP을 지원합니다. 이 기능은 BlueXP  랜섬웨어 방어 기능으로 FSx for ONTAP 워크로드를 보호하는 데 도움이 됩니다.

FSx for ONTAP은 클라우드에서 NetApp ONTAP 스토리지의 강력한 기능을 제공하는 완전 관리형 서비스입니다. 또한 네이티브 AWS 서비스의 민첩성 및 확장성과 함께 사내에서 사용하는 것과 동일한 기능, 성능, 관리 기능을 제공합니다.

BlueXP  랜섬웨어 방어 워크플로우가 다음과 같이 변경되었습니다.

* 검색 기능에는 FSx for ONTAP 9.15 작업 환경의 워크로드가 포함됩니다.
* 보호 탭에는 FSx for ONTAP 환경의 워크로드가 표시됩니다. 이 환경에서는 FSx for ONTAP 백업 서비스를 사용하여 백업 작업을 수행해야 합니다. BlueXP  랜섬웨어 방지 스냅샷을 사용하여 이러한 워크로드를 복원할 수 있습니다.
+

TIP: FSx for ONTAP에서 실행되는 워크로드의 백업 정책을 BlueXP 에서 설정할 수 없습니다. Amazon FSx for NetApp ONTAP에서 설정된 기존 백업 정책은 변경되지 않고 그대로 유지됩니다.

* 경고 인시던트에는 새로운 FSx for ONTAP 작업 환경이 표시됩니다.


자세한 내용은 을 https://docs.netapp.com/us-en/bluexp-ransomware-protection/concept-ransomware-protection.html["BlueXP  랜섬웨어 방지 및 작업 환경에 대해 알아보십시오"]참조하십시오.

지원되는 옵션에 대한 자세한 내용은 를 https://docs.netapp.com/us-en/bluexp-ransomware-protection/rp-reference-limitations.html["BlueXP  랜섬웨어 방지 제한 사항"]참조하십시오.



==== BlueXP 액세스 역할이 필요합니다

이제 BlueXP 랜섬웨어 보호를 보고, 검색하고, 관리하려면 다음 액세스 역할 중 하나가 필요합니다. 조직 관리자, 폴더 또는 프로젝트 관리자, 랜섬웨어 보호 관리자 또는 랜섬웨어 보호 뷰어.

https://docs.netapp.com/us-en/bluexp-setup-admin/reference-iam-predefined-roles.html["모든 서비스에 대한 BlueXP 액세스 역할에 대해 알아보세요"^]..



=== 2025년 4월 14일



==== 준비 훈련 보고서

이번 릴리즈에서는 랜섬웨어 공격 준비도 훈련 보고서를 검토할 수 있습니다. 준비도 드릴을 사용하여 새로 생성된 샘플 워크로드에 대한 랜섬웨어 공격을 시뮬레이션할 수 있습니다. 그런 다음 시뮬레이션된 공격을 조사하고 샘플 워크로드를 복구합니다. 이 기능은 알림, 응답 및 복구 프로세스를 테스트하여 실제 랜섬웨어 공격이 발생했을 때 적절한 준비가 되어 있는지 파악하는 데 도움이 됩니다.

자세한 내용은 을 https://docs.netapp.com/us-en/bluexp-ransomware-protection/rp-start-simulate.html["랜섬웨어 공격 준비도 훈련을 실시합니다"]참조하십시오.



==== 새로운 역할 기반 액세스 제어 역할 및 권한

이전에는 자신의 책임에 따라 사용자에게 역할과 권한을 할당함으로써 BlueXP  랜섬웨어 방어에 대한 사용자 액세스를 관리하는 데 도움이 될 수 있었습니다. 이 릴리즈에서는 업데이트된 권한이 있는 BlueXP  랜섬웨어 보호와 관련된 두 가지 새로운 역할이 있습니다. 새로운 역할은 다음과 같습니다.

* 랜섬웨어 차단 관리자
* 랜섬웨어 방어 뷰어


사용 권한에 대한 자세한 내용은 을 https://docs.netapp.com/us-en/bluexp-ransomware-protection/rp-reference-roles.html["기능에 대한 BlueXP  랜섬웨어 방지 역할 기반 액세스"]참조하십시오.



==== 지불 개선

이 릴리스에는 결제 프로세스에 대한 몇 가지 개선 사항이 포함되어 있습니다.

자세한 내용은 을 https://docs.netapp.com/us-en/bluexp-ransomware-protection/rp-start-licenses.html["라이선스 및 결제 옵션을 설정합니다"]참조하십시오.



== 해결

BlueXP 개선 서비스가 2024년 4월 22일에 제거되었습니다.



== 복제



=== 2022년 9월 18일



==== ONTAP에서 Cloud Volumes ONTAP로 FSX

이제 ONTAP 파일 시스템용 Amazon FSx에서 Cloud Volumes ONTAP로 데이터를 복제할 수 있습니다.

https://docs.netapp.com/us-en/bluexp-replication/task-replicating-data.html["데이터 복제를 설정하는 방법에 대해 알아보십시오"].



=== 2022년 7월 31일



==== ONTAP용 FSX를 데이터 소스로 사용합니다

이제 Amazon FSx for ONTAP 파일 시스템에서 다음 대상으로 데이터를 복제할 수 있습니다.

* ONTAP용 Amazon FSx
* 사내 ONTAP 클러스터


https://docs.netapp.com/us-en/bluexp-replication/task-replicating-data.html["데이터 복제를 설정하는 방법에 대해 알아보십시오"].



=== 2021년 9월 2일



==== ONTAP용 Amazon FSx 지원

이제 Cloud Volumes ONTAP 시스템 또는 온프레미스 ONTAP 클러스터에서 ONTAP 파일 시스템용 Amazon FSx로 데이터를 복제할 수 있습니다.

https://docs.netapp.com/us-en/bluexp-replication/task-replicating-data.html["데이터 복제를 설정하는 방법에 대해 알아보십시오"].



== 소프트웨어 업데이트



=== 2025년 5월 12일



==== BlueXP 액세스 역할이 필요합니다

이제 소프트웨어 업데이트를 설치하려면 다음 액세스 역할 중 하나가 필요합니다. *조직 관리자*, *폴더 또는 프로젝트 관리자*, *저장소 관리자*, *저장소 뷰어* 또는 *저장소 상태 전문가*. 저장소 뷰어 역할을 가진 사용자는 소프트웨어 업데이트와 관련된 다양한 권한을 가지지만 소프트웨어 업데이트를 설치할 수는 없습니다. link:https://docs.netapp.com/us-en/bluexp/concept-iam-predefined-roles.html["BlueXP 액세스 역할에 대해 알아보세요."^]



=== 2025년 4월 2일



==== 위험 완화

이제 BlueXP  소프트웨어 업데이트의 요약 섹션에서 운영 체제 업데이트로 완화할 수 있는 총 위험 수를 볼 수 있습니다. 이를 통해 사용자는 설치 기반에서 보안 및 안정성 향상을 평가할 수 있습니다.



=== 2024년 8월 7일



==== ONTAP 업데이트

BlueXP  소프트웨어 업데이트 서비스는 위험을 완화하고 고객이 ONTAP 기능을 최대한 활용할 수 있도록 함으로써 사용자에게 원활한 업데이트 환경을 제공합니다.

에 대해 자세히 link:https://docs.netapp.com/us-en/bluexp-software-updates/get-started/software-updates.html["BlueXP  소프트웨어 업데이트"]알아보십시오.



== StorageGRID



=== 2025년 5월 12일



==== BlueXP 액세스 역할이 필요합니다

이제 BlueXP 에서 StorageGRID 보거나 검색하거나 관리하려면 다음 액세스 역할 중 하나가 필요합니다. *조직 관리자*, *폴더 또는 프로젝트 관리자*, *스토리지 관리자* 또는 *스토리지 상태 전문가*. link:https://docs.netapp.com/us-en/bluexp/reference-iam-predefined-roles.html["BlueXP 액세스 역할에 대해 알아보세요."^]



=== 2024년 8월 7일



==== 새로운 고급 보기

StorageGRID 11.8부터 친숙한 그리드 관리자 인터페이스를 사용하여 BlueXP 에서 StorageGRID 시스템을 관리할 수 있습니다.

https://docs.netapp.com/us-en/bluexp-storagegrid/task-administer-storagegrid.html["고급 보기를 사용하여 StorageGRID를 관리하는 방법에 대해 알아봅니다"]..



==== StorageGRID 관리 인터페이스 인증서를 검토하고 승인할 수 있습니다

이제 BlueXP 에서 StorageGRID 시스템을 검색할 때 StorageGRID 관리 인터페이스 인증서를 검토하고 승인할 수 있습니다. 검색된 그리드에서 최신 StorageGRID 관리 인터페이스 인증서를 검토하고 승인할 수도 있습니다.

https://docs.netapp.com/us-en/bluexp-storagegrid/task-discover-storagegrid.html["시스템 검색 중에 서버 인증서를 검토하고 승인하는 방법에 대해 알아봅니다."]



=== 2022년 9월 18일



==== StorageGRID 지원

이제 BlueXP에서 직접 StorageGRID 시스템을 검색할 수 있습니다. StorageGRID을 발견하여 하이브리드 멀티 클라우드 전체의 데이터를 완벽하게 파악할 수 있습니다.



== 계층화



=== 2023년 8월 9일



==== 버킷 이름에 사용자 지정 접두사를 사용합니다

이전에는 버킷 이름을 정의할 때 기본 "fabric-pool" 접두사를 사용해야 했습니다(예: _fabric-pool-bucket1_). 이제 버킷 이름을 지정할 때 사용자 지정 접두사를 사용할 수 있습니다. 이 기능은 데이터를 Amazon S3로 계층화하는 경우에만 사용할 수 있습니다. https://docs.netapp.com/us-en/bluexp-tiering/task-tiering-onprem-aws.html#prepare-your-aws-environment["자세한 정보"].



==== 모든 BlueXP Connector에서 클러스터를 검색합니다

사용자 환경의 모든 스토리지 시스템을 관리하기 위해 여러 커넥터를 사용하는 경우 계층화를 구현할 클러스터가 다른 커넥터에 있을 수 있습니다. 어떤 커넥터가 특정 클러스터를 관리하고 있는지 확실하지 않은 경우 BlueXP 계층화를 사용하여 모든 커넥터를 검색할 수 있습니다. https://docs.netapp.com/us-en/bluexp-tiering/task-managing-tiering.html#search-for-a-cluster-across-all-bluexp-connectors["자세한 정보"].



=== 2023년 7월 4일



==== 대역폭을 조정하여 비활성 데이터를 전송합니다

BlueXP 계층화를 활성화하면 ONTAP는 무제한의 네트워크 대역폭을 사용하여 클러스터의 볼륨에서 객체 스토리지로 비활성 데이터를 전송할 수 있습니다. 계층화 트래픽이 정상적인 사용자 워크로드에 영향을 미치는 경우 전송 중에 사용할 수 있는 대역폭의 양을 조절할 수 있습니다. https://docs.netapp.com/us-en/bluexp-tiering/task-managing-tiering.html#changing-the-network-bandwidth-available-to-upload-inactive-data-to-object-storage["자세한 정보"]..



==== 알림 센터에 계층화 이벤트가 표시됩니다

계층화 이벤트 "Tier additional data from cluster <name> to object storage to increase storage Efficiency"는 이제 클러스터가 데이터를 계층화하는 경우를 포함하여 콜드 데이터의 20% 미만을 계층화할 때 알림으로 표시됩니다.

이 알림은 시스템의 효율성을 높이고 스토리지 비용을 절감하는 데 도움이 되는 "권장 사항"입니다. 에 대한 링크를 제공합니다 https://bluexp.netapp.com/cloud-tiering-service-tco["BlueXP 계층화 총 소유 비용 및 절감 계산기"^] 비용 절감 효과를 계산하는 데 도움이 됩니다.



=== 2023년 4월 3일



==== 라이센스 탭이 제거되었습니다

BlueXP 계층화 인터페이스에서 라이센스 탭이 제거되었습니다. PAYGO(pay-as-you-go) 서브스크립션에 대한 모든 라이센스는 이제 BlueXP 계층화 온-프레미스 대시보드에서 액세스할 수 있습니다. 또한 BlueXP 계층화 기능을 통해 BYOL(Bring-Your-Own-License)을 확인하고 관리할 수 있도록 해당 페이지에서 BlueXP 디지털 지갑까지 연결되는 링크도 있습니다.



==== 계층화 탭의 이름이 변경되고 업데이트되었습니다

"클러스터 대시보드" 탭의 이름이 "클러스터"로 바뀌고 "온프레미스 개요" 탭의 이름이 "온-프레미스 대시보드"로 바뀌었습니다. 이러한 페이지에는 추가 계층화 구성으로 스토리지 공간을 최적화할 수 있는지 평가하는 데 도움이 되는 몇 가지 정보가 추가되었습니다.



== 볼륨 캐싱



=== 2023년 6월 4일



==== 볼륨 캐싱

ONTAP 9 소프트웨어의 기능인 볼륨 캐싱은 파일 배포를 간소화하고, 사용자와 컴퓨팅 리소스의 위치에 리소스를 더 가깝게 배치함으로써 WAN 대기 시간을 줄이고, WAN 대역폭 비용을 절감하는 원격 캐싱 기능입니다. 볼륨 캐싱은 원격 위치에서 쓰기 가능한 영구 볼륨을 제공합니다. BlueXP 볼륨 캐싱을 사용하여 데이터 액세스 속도를 높이거나 자주 액세스하는 볼륨에서 트래픽을 오프로드할 수 있습니다. 캐시 볼륨은 특히 클라이언트가 동일한 데이터에 반복적으로 액세스해야 하는 읽기 집약적인 워크로드에 적합합니다.

BlueXP 볼륨 캐싱을 사용하면 클라우드에 대한 캐싱 기능이 있으며, 특히 NetApp ONTAP, Cloud Volumes ONTAP 및 온-프레미스에서 작업 환경으로 사용되는 Amazon FSx를 지원합니다.

link:https://docs.netapp.com/us-en/bluexp-volume-caching/get-started/cache-intro.html["BlueXP 볼륨 캐싱에 대해 자세히 알아보십시오"].



== 워크로드 공장



=== 2025년 6월 29일



==== 데이터베이스에 대한 사용 권한 업데이트

다음 권한은 이제 데이터베이스에 대한 _읽기 전용_ 모드에서 사용 가능합니다.  `cloudwatch:GetMetricData` .

https://docs.netapp.com/us-en/workload-setup-admin/permissions-reference.html#change-log["권한 참조 변경 로그"]



==== BlueXP 워크로드 팩토리 알림 서비스 지원

BlueXP 워크로드 팩토리 알림 서비스를 사용하면 워크로드 팩토리가 BlueXP 알림 서비스 또는 Amazon SNS 주제로 알림을 전송할 수 있습니다. BlueXP 알림으로 전송된 알림은 BlueXP 알림 패널에 표시됩니다. 워크로드 팩토리가 Amazon SNS 주제에 알림을 게시하면 해당 주제 구독자(예: 사용자 또는 다른 애플리케이션)는 해당 주제에 대해 구성된 엔드포인트(예: 이메일 또는 SMS 메시지)에서 알림을 수신합니다.

https://docs.netapp.com/us-en/workload-setup-admin/configure-notifications.html["BlueXP 워크로드 팩토리 알림 구성"]



=== 2025년 5월 4일



==== CloudShell 자동 지원

BlueXP  워크로드 팩토리 CloudShell을 사용하는 경우 명령 입력을 시작하고 Tab 키를 눌러 사용 가능한 옵션을 볼 수 있습니다. 가능성이 여러 개인 경우 CLI에 제안 목록이 표시됩니다. 이 기능은 오류를 최소화하고 명령 실행 속도를 높여 생산성을 향상시킵니다.



==== 사용 권한 용어가 업데이트되었습니다

워크로드 팩토리 사용자 인터페이스와 문서에서는 이제 읽기 권한을 나타내는 데 "읽기 전용"을 사용하고 자동화 권한을 나타내는 데 "읽기/쓰기"를 사용합니다.



=== 2025년 3월 30일



==== CloudShell은 ONTAP CLI 명령에 대한 AI에서 생성된 오류 응답을 보고합니다

CloudShell을 사용할 경우 ONTAP CLI 명령을 실행하고 오류가 발생할 때마다 실패 설명, 장애 원인, 상세한 해결 방법 등을 통해 AI에서 생성된 오류에 대한 응답을 받을 수 있습니다.

link:https://docs.netapp.com/us-en/workload-setup-admin/use-cloudshell.html["CloudShell을 사용합니다"]



==== IAM: SimulatePermissionPolicy 권한 업데이트

이제 AWS 계정 자격 증명을 추가하거나 GenAI 워크로드와 같은 새로운 워크로드 기능을 추가할 때 워크로드 팩토리 콘솔에서 권한을 관리할 수 있습니다 `iam:SimulatePrincipalPolicy`.

link:https://docs.netapp.com/us-en/workload-setup-admin/permissions-reference.html#change-log["권한 참조 변경 로그"]



=== 2025년 2월 2일



==== BlueXP  워크로드 공장 콘솔에서 사용할 수 있는 CloudShell

CloudShell은 BlueXP  워크로드 공장 콘솔의 모든 곳에서 사용할 수 있습니다. CloudShell을 사용하면 BlueXP  계정에 제공한 AWS 및 ONTAP 자격 증명을 사용하고 셸 유사 환경에서 AWS CLI 명령 또는 ONTAP CLI 명령을 실행할 수 있습니다.

link:https://docs.netapp.com/us-en/workload-setup-admin/use-cloudshell.html["CloudShell을 사용합니다"]



==== 데이터베이스에 대한 사용 권한 업데이트

이제 데이터베이스에 대해 _READ_MODE에서 다음 권한을 사용할 수 `iam:SimulatePrincipalPolicy` 있습니다.

link:https://docs.netapp.com/us-en/workload-setup-admin/permissions-reference.html#change-log["권한 참조 변경 로그"]
