= S3 구성 ONTAP 시스템의 버킷에 볼륨을 백업하도록 지원이 추가되었습니다
:allow-uri-read: 


[IMPORTANT]
====
* 중요한 보안 개선 사항으로 인해 이제 Connector는 공용 클라우드 환경 내에서 백업 및 복구 리소스를 관리하기 위해 추가 엔드포인트에 대한 아웃바운드 인터넷 액세스를 필요로 합니다. 이 끝점이 방화벽의 "허용" 목록에 추가되지 않은 경우 UI에 "서비스를 사용할 수 없음" 또는 "서비스 상태 확인 실패"에 대한 오류가 표시됩니다.
+
\https://netapp-cloud-account.auth0.com

* Cloud Volumes ONTAP 및 BlueXP 백업 및 복구를 번들로 제공할 수 있는 "CVO Professional" 패키지를 사용하는 경우 백업 및 복구 PAYGO 가입이 필요합니다. 과거에는 필요하지 않았습니다. 적격 Cloud Volumes ONTAP 시스템의 백업 및 복구 서브스크립션에는 비용이 청구되지 않지만 새 볼륨에 백업을 구성할 때 비용이 필요합니다.


====


=== S3 구성 ONTAP 시스템의 버킷에 볼륨을 백업하도록 지원이 추가되었습니다

이제 S3(Simple Storage Service)로 구성된 ONTAP 시스템을 사용하여 볼륨을 오브젝트 스토리지에 백업할 수 있습니다. 이는 온프레미스 ONTAP 시스템과 Cloud Volumes ONTAP 시스템 모두에서 지원됩니다. 이 구성은 인터넷 액세스가 없는 클라우드 배포 및 사내 위치("전용" 모드 배포)에서 지원됩니다.

https://docs.netapp.com/us-en/bluexp-backup-recovery/task-backup-onprem-to-ontap-s3.html["자세한 정보"].



=== 이제 백업 파일에 보호된 볼륨의 기존 스냅샷을 포함할 수 있습니다

과거에는 최신 스냅샷 복사본으로 시작하는 것이 아니라, 초기 백업 파일에 읽기-쓰기 볼륨의 기존 Snapshot 복사본을 오브젝트 스토리지에 포함하는 기능이 있었습니다. 읽기 전용 볼륨(데이터 보호 볼륨)의 기존 스냅샷 복사본은 백업 파일에 포함되지 않았습니다. 이제 "DP" 볼륨의 백업 파일에 이전 Snapshot 복사본을 포함하도록 선택할 수 있습니다.

백업 마법사가 백업 단계 끝에 이러한 "기존 스냅샷"을 선택할 수 있는 프롬프트를 표시합니다.



=== BlueXP 백업 및 복구는 이후에 추가된 볼륨의 자동 백업을 더 이상 지원하지 않습니다

이전에는 백업 마법사에서 확인란을 선택하여 선택한 백업 정책을 클러스터에 추가되는 모든 볼륨에 적용할 수 있었습니다. 이 기능은 사용자 피드백 및 이 기능의 사용 부족을 기준으로 제거되었습니다. 클러스터에 추가된 새 볼륨에 대해 백업을 수동으로 활성화해야 합니다.



=== 작업 모니터링 페이지가 새로운 기능으로 업데이트되었습니다

이제 작업 모니터링 페이지에서 3-2-1 백업 전략과 관련된 자세한 정보를 확인할 수 있습니다. 이 서비스는 백업 전략과 관련된 추가 알림 알림도 제공합니다.

"백업 수명 주기" 유형 필터의 이름이 "보존"으로 변경되었습니다. 이 필터를 사용하여 백업 라이프사이클을 추적하고 모든 백업 복제본의 만료 날짜를 식별합니다. "보존" 작업 유형은 BlueXP 백업 및 복구로 보호되는 볼륨에서 시작된 모든 스냅샷 삭제 작업을 캡처합니다.

https://docs.netapp.com/us-en/bluexp-backup-recovery/task-monitor-backup-jobs.html["업데이트된 작업 모니터에 대해 자세히 알아보십시오"].
